index.html
index.xml
v1.html
v1.xml

By hooking up interface object prototype chains to follow the interface inheritance chain, which is how ES6 classes that extend each other work.

Fix https://www.w3.org/Bugs/Public/show_bug.cgi?id=23133

---

index.xml

All `@@toStringTag` instances, short of `Symbol.toStringTag` (where it's exposed as a public API), are configurable in ES6 --- although not everyone is happy about that. It's likely to stay that way

Fix a typo in editorial note for @@toStringTag

---

index.html
index.xml

@bzbarsky can you take a look at this, as a solution to https://www.w3.org/Bugs/Public/show_bug.cgi?id=23682?

Fix arrays

---

index.html
index.xml

1. iterable<> declarations with a single type ("value iterators") now
always iterates over the object's indexed properties, and disallows
its use on objects that don't support indexed properties (and have a
"length" attribute).
2. The entries and keys properties of interface prototypes for
interfaces that have value iterators are now defined to have values
equal to the initial values of Array.prototype.{entries,keys},
similarly to how @@iterator was already defined when indexed
properties were present.
3. The definitions of @@iterator and forEach for iterable<> declarations
with two types ("pair iterators") are fixed.  "Default iterator
objects" now work only for pair iterators, since we don't support
prose-defined value iterators now.

Fix some problems with iterable declarations.

---

index.xml

Adds [appropriate markup](https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md) to all of the `<dfn>` elements in WebIDL, so the spec can be added to Shepherd and linked properly by all Bikeshedded specs.  Nearly all of the definitions are reasonable to export and link to.
Also adds appropriate markup to the `<h4>`s for several IDL types that don't otherwise have a `<dfn>` element (because everything in the spec just links to the section instead).

Make all the WebIDL dfns Bikeshed-friendly

---

index.xml

* The heading-dfns need to have their linking text set explicitly; right now they're including the section number inserted by XSLT.
* The simple errors should be dfn'd, I think.  (Until ES is Bikeshed-friendly, at least.)
* The DOMException types should be "exception" type.  (I misunderstood what they were previously.)

Bikeshed-link fixes

---

index.html
index.xml

jorendorff's unofficial HTML version already redirects there, so there's no
point in linking to that URL.
This commit only updates the links; more work is needed to ensure all
references are still correct in ES2017.

Update links to ES2017.

---

index.xml

FYI @mvano @foolip re https://github.com/w3c/push-api/issues/186.
This fixes #95.

Document that NotAllowedError should be used for denied permissions.

---

index.html
index.xml

This updates the four algorithms that invoke user code in the following ways:
- Updates them to use HTML's latest framework for managing script settings objects. The previous version referred to concepts, such as the "stack of incumbent scripts", which have not been defined for a long time (i.e. since before whatwg/html#401). Updates in whatwg/html#401 and whatwg/html#1091 have changed the setup here. There is still some ongoing discussion in whatwg/html#473 about whether the current HTML setup is correct for managing _incumbent_ settings objects, but this at least updates the algorithms to correctly manage _entry_ settings objects. The plan implemented here is roughly that discussed in https://github.com/whatwg/html/issues/473#issuecomment-212164549.
- Gives them explicit `<dfn>`s with …

Modernize invoking user code

---

index.html
index.xml

This is the counterpart to https://github.com/whatwg/html/pull/1189, and properly calls in to HTML's new hooks to handle tracking the incumbent settings object using Web IDL's callback context mechanisms.

Fix incumbent settings object handling

---

index.html
index.xml

This adds the concept of namespaces, as discussed in https://github.com/whatwg/console/issues/3 (starting especially around https://github.com/whatwg/console/issues/3#issuecomment-214586757). They can only contain regular operations.
The ES binding for namespaces here is written in a fully modern style, and so differs slightly from similar prose for interfaces' ES binding. It is hoped that it can provide a template for eventually updating interfaces' ES binding to modern ES.

Add namespaces

---

index.html
index.xml

/cc @foolip who was looking at this with me this morning

Add some IDs to callback-invoking definitions

---

index.bs
index.html

This consolidates the spec text for creating the functions for interface operations and namespace operations, using the more modern style seen in namespace operations (introduced in df8c9c4ef7e32298ea3b8b13eed73790957468da) as the base.
Along the way, this fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=18547 (making all methods [ImplicitThis], and getting rid of [ImplicitThis]), and fixes https://github.com/whatwg/html/issues/643 (a related issue on the HTML side).
This also fixes #106, since we now explicitly use the CreateBuiltinFunction abstract operation.
---
@bzbarsky please take a look! I'm rather pleased that this managed to fix the long-standing [ImplicitThis] issue.

Update method creation for operations

---

index.bs
index.html

I would have liked to get rid of the always-redundant "This version:" but Bikeshed won't let you do that for anything that's marked as an ED (instead of a LS).

Consolidate issue tracking links in the header under "Feedback"

---

index.bs
index.html

Fixes <https://github.com/heycam/webidl/issues/152>.

Change the named property visibility algorithm so that existing own props always make corresponding named props invisible.

---

Makefile

Make defaults to API when Bikeshed isn’t installed locally.

---

index.bs
index.html

This feature was introduced by #13, but the main thing we actually
needed for Headers et al was open dictionaries (see #180). As such this
feature has not seen any use.

Remove "initializing objects from iterables"

---

index.bs
index.html

Fix distinguishable algorithm. Closes #190.
Fix record handling in various algorithms. Closes #191, closes #189.
<hr />
[Preview](https://rawgit.com/tobie/webidl/fix-180/index.html) (<a href="https://rawgit.com/tobie/webidl/fix-180/index.html#dfn-distinguishable" title="#dfn-distinguishable">#dfn-disti…</a>) (<a href="https://rawgit.com/tobie/webidl/fix-180/index.html#es-union" title="#es-union">#es-union</a>) (<a href="https://rawgit.com/tobie/webidl/fix-180/index.html#es-overloads" title="#es-overloads">#es-overlo…</a>) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Ftobie%2Fwebidl%2Ffix-180%2Findex.html) (<a href="https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fr …

Various follow-up fixes to #180.

---

index.bs
index.html

This PR:
* marks up all algorithms with `<div algorithm>`,
* gives a name to those which don't include a `<dfn>`,
* ~~turns single step algorithms (e.g. `return false`) to prose.~~
* Fix algorithms that generated Bikeshed warnings (due to missing variables or mistakes in variable names).
This PR is too big to be apprehended as a whole in GitHub, however it's split into explicitly named commits.
The first commit is just a markup change, as shown by its [HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fb6b4453%2Findex.html).
Every following commit is atomic and addresses a particular issue raised by Bikeshed.
<hr />
[Preview](https://rawgit.com/tobie/webidl/algos/index.html) | …

Use Bikeshed’s algorithm construct.

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29384.
***
[Preview](https://rawgit.com/heycam/webidl/annevk/remove-unforgeable-interfaces/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Fheycam%2Fwebidl%2Fannevk%2Fremove-unforgeable-interfaces%2Findex.html)

Remove support for [Unforgeable]-annotated interfaces

---

index.bs
index.html

Fixes #62.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=22808.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/208dbe3/index.html#es-constructible-interfaces) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F208dbe3%2Findex.html#es-constructible-interfaces) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fd8901f6%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F208dbe3%2Findex.html#es-constructible-interfaces)

Throw when not calling interfaces as constructors

---

index.bs

***
[Preview](https://cdn.rawgit.com/TimothyGu/webidl/f324d60/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2FTimothyGu%2Fwebidl%2Ff324d60%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fbbb2bde%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2FTimothyGu%2Fwebidl%2Ff324d60%2Findex.html)

Fix typo in sequence type conversion example

---

index.bs
index.html

Some Chrome devs were confused by the current phrasing of "value is the result of calling the [[Get]] internal method of V passing key and V as arguments" as it's not explicit about rethrowing exceptions. While I was there I cleaned up other stuff.
***
[Preview](https://cdn.rawgit.com/heycam/webidl/029b456/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F029b456%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F7dde1ff%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F029b456%2Findex.html)

Modernize and clean up dictionary type conversions

---

index.bs
index.html

* Add legacy platform object dfn.
* Only allow defining legacy callers on interfaces that support
named/indexed props.
* Disallow indexed prop getters on globals.
* Move all named/indexed prop methods to legacy platform objects.
* Move legacy caller method to legacy platform objects.
Fixes #202.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/8bc5df5/index.html) (<a href="https://cdn.rawgit.com/tobie/webidl/8bc5df5/index.html#idl-legacy-callers" title="#idl-legacy-callers">#idl-leg…</a>) (<a href="https://cdn.rawgit.com/tobie/webidl/8bc5df5/index.html#idl-objects" title="#idl-objects">#idl-obj…</a>) (<a href="https://cdn.rawgit.com/tobie/webidl/8bc5df5/index.html#Global" title="#Global">#Global</a>) (<a href="https://cdn.rawgit.com/tobie/webidl/8bc5df5/index.html#named-properties-object" …

Add legacy platform objects.

---

index.bs
index.html

And also stop marking them up as Bikeshed IDL types since they’re not.
See also #233 and #240 though I don’t think this commit addresses
either of them fully.
***
[Preview](https://cdn.rawgit.com/heycam/webidl/daeea0b/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fdaeea0b%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fa0b2c0c%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fdaeea0b%2Findex.html)

Meta: export record and sequence

---

index.bs
index.html

Since this is not done for records, confuses Shepherd, and is not used
by IDL itself, let’s get rid of it.
***
[Preview](https://cdn.rawgit.com/heycam/webidl/6cf2daf/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F6cf2daf%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fd99fdf9%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F6cf2daf%2Findex.html)

Meta: remove sequence<T> as Bikeshed definition

---

index.bs
index.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=27284.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/c124a10/index.html#invalidaccesserror) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fc124a10%2Findex.html#invalidaccesserror) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fafcc257%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fc124a10%2Findex.html#invalidaccesserror)

Deprecate InvalidAccessError.

---

index.bs
index.html

* Don't define simple exception names in WebIDL.
* Make Error exclusively for authors.
* Fix syntax for throwing and creating DomExceptions.
* Fix examples.
Closes #247.
**NOTE:** This doesn't address the distinction between [#throw](https://heycam.github.io/webidl/#dfn-throw) and [#ecmascript-throw](https://heycam.github.io/webidl/#ecmascript-throw), which I think needs fixing before we merge this.
I'd be tempted not to export [#ecmascript-throw](https://heycam.github.io/webidl/#ecmascript-throw) and make everything use [#throw](https://heycam.github.io/webidl/#dfn-throw) instead. (Currently all simple exceptions in the spec reference [#ecmascript-throw](https://heycam.github.io/webidl/#ecmascript-throw), which I don't think is the right thing to do.)
We'd then only use the text around …

Exception cleanup

---

index.bs
index.html

- Fixes getters on the global when no explicit `this` is passed, similarly to what was already done for operations in a2b4599631fe0fa254a7a4993dd7f00b74c8ad20. Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29421.
- Make promise getters reject in case of an error. Disallow promise types on attributes that will generate setters. Fixes #186 and fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25048.
- Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=27905 by more clearly specifying the target (as was done previously for operations).
- Updated to use modern ES Get/Set abstract operations instead of [[Get]] and [[Put]].
- Also made minor fixes to the operations definition, e.g. wrapping it in `<div algorithm>` and remembering to actually return F.
*** …

Update attribute setter/getters in various ways

---

index.bs
index.html

This mutes the escape backslashes of the comment terminal symbol regex.
It's more correct and makes it easier to programatically extract the regexes for a lexer.
/cc @heycam
***
[Preview](https://cdn.rawgit.com/tobie/webidl/15e54a3/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F15e54a3%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F4c9c298%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F15e54a3%2Findex.html)

Mute escape backslashes of terminal symbol regexes.

---

index.bs
index.html

Closes #168.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/23d2c5f/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F23d2c5f%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F68b4d84%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F23d2c5f%2Findex.html)

Meta: remove unnecessary spans around property descriptors.

---

index.bs
index.html

***
[Preview](https://cdn.rawgit.com/tobie/webidl/29003c6/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F29003c6%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F0b1a510%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F29003c6%2Findex.html)

Editorial: use Type(x) were appropriate.

---

index.bs
index.html

Primarily by grouping types into larger categories, but also by recategorizing callback interfaces as more like dictionaries than normal interfaces.
Fixes #50 and #59.
***
[Preview](https://cdn.rawgit.com/jyasskin/webidl/6a5406a/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fjyasskin%2Fwebidl%2F6a5406a%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Ffef2cda%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fjyasskin%2Fwebidl%2F6a5406a%2Findex.html)

Simplify the distinguishable table.

---

index.bs
index.html

This is on top of #217 so only look at the second commit if you want an accurate diff of the feature.
The example has a commented out line until we can update Bikeshed's Web IDL parser. Probably we should not land things like this.
The main thing that would be helpful to review here is that I didn't forgot other places in the spec that need modifying. I did manage to remember to update all the extended attributes (basically disallowing them all except [NewObject]/[SameObject]).
***
[Preview](https://cdn.rawgit.com/heycam/webidl/4644d0d/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F4644d0d%2Findex.html) | [Diff w/ …

Attributes on namespaces

---

index.bs
index.html

Closes #80.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/2df687b/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F2df687b%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fca94c43%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F2df687b%2Findex.html)

Interfaces with indexed properties must have a length attribute

---

index.bs
index.html

Introduce light styling for deprecated content.
Closes #284.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/ba0187c/index.html#idl-DOMException-error-names) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fba0187c%2Findex.html#idl-DOMException-error-names) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F3834774%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fba0187c%2Findex.html#idl-DOMException-error-names)

Merge deprecated DOMException names back into the main table.

---

index.bs

Say "interfaces that also support", not "interfaces that also supports".

Adjust wording in the legacy callers section.

---

index.bs
index.html

See: https://github.com/tc39/ecma262/commit/390234dd4260504fc6e9f40c79fa50cc5256be95.
Fixes #288.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/5b30416/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F5b30416%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fe5d04d0%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F5b30416%2Findex.html)

Editorial: use recently added ids to ES math equations.

---

index.bs
index.html

***
[Preview](https://cdn.rawgit.com/jyasskin/webidl/4253081/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fjyasskin%2Fwebidl%2F4253081%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fc1ff4b2%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fjyasskin%2Fwebidl%2F4253081%2Findex.html)

Fix #296: ban dictionary recursion through records.

---

index.bs
index.html

Closes #292, in particular by removing the nonsensical "current global environment" concept and switching the example to reflect the desired semantics instead of the opposite.
This commit also modernizes the section and fixes a few small bugs, such as the omission of the message for the DOMException case, or the attempt to call the DOMException constructor as a function, which in most implementations will throw.
***
[Preview](https://cdn.rawgit.com/heycam/webidl/977f043/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F977f043%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F662b008%2Findex.html&doc2=htt …

Clarify that exceptions are always thrown in the current Realm

---

index.bs
index.html

Basically, make record<> more like sequence<> than like dictionary in terms of things that can be converted to it (without the requirement for iterability, of course)
***
[Preview](https://s3.amazonaws.com/pr-preview/bzbarsky/webidl/record-not-dictionarylike.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/8c11c7e..bzbarsky:record-not-dictionarylike:c3530c7.html)

Allow records to be nullable in all cases and omitted as optional operation arguments.

---

index.bs

* Extract legacy callback interface objects
out of interface objects. Closes #78.
* Clarify that legacy callback interfaces are function objects.
* Give them a length property. Closes #279. Closes #83.
* Require new for Named Constructors. Closes #275.
* Rely on ES abstract operations for defining
named constructors, interface objects, and
legacy callback interface objects.
* Disallow using [NoInterfaceObject] on
callback interfaces with constants.
* Don't require an interface prototype object for constants.
Callback interfaces do not have an interface prototype object.
Their constants sit on the legacy callback interface object itself.
Closes #281.
Closes #283.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/interface-objs.html) | …

Revamp interface bindings

---

index.bs

Debounce scroll events.
Only update the DOM during requestAnimationFrame.
Closes #314.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-scroll.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/4a8f57e..tobie:fix-scroll:1155a70.html)

Meta: Fix scroll jank

---

index.bs

Explicitly convert −0 to +0.
Closes #306.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-306.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/eb272b6..tobie:fix-306:4006c6b.html)

Carry out math operations on real numbers, not IEEE 754.

---

index.bs

This closes whatwg/infra#4 and whatwg/infra#65. It also helps a bit with #242.
/cc @jyasskin @annevk
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/infra-integration.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/6b2bbb3..infra-integration:287684d.html)

Base sequences, dictionaries, and records on Infra types

---

index.bs

Also change how it's linked to a little bit.
See https://github.com/whatwg/fetch/issues/513 for the motivation.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/present.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/fe42994...4442344.html)

Note what "present" means in ES close to its definition

---

index.bs

This helps move some of the heavy lifting into IDL, to avoid issues like https://github.com/whatwg/html/issues/2381.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/construct-helper.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/fe42994...d445e3f.html)

Add the ability to construct a callback function

---

index.bs

This implements the plan discussed in https://lists.w3.org/Archives/Public/public-script-coord/2017JanMar/0003.html and sets the stage for using extended attributes for SharedArrayBuffer-related purposes.
@bzbarsky, I could use some close review on this. Some points for discussion:
- Is `[Clamp] long` being a distinct type from `long` a good way of doing this? I based that on how `long?` is different from `long`, and it seems like a good mental model.
- Is it sufficiently clear that extended attributes propagate through typedefs? (A point you called out specifically in your email.) If not, any suggestions on how to make this clear?
- We have separate TypeWithAttributes and Type mainly so that ReturnType does not get attributes. Does that seem good?
- I didn't allow (gramatically) …

Allow extended attributes to apply to types

---

index.bs

Fixes #343.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-343.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/faaaaa9...tobie:2831845.html)

Deprecate "IndexSizeError" DOMException.

---

index.bs

Previous to this commit, any API that accepted any of the buffer source types would also accept a SharedArrayBuffer. This was not the approach we want; instead, we want APIs to explicitly opt-in. Enabled by previous work creating annotated types, this adds the new [AllowShared] extended attribute to allow APIs to opt in to accepting SharedArrayBuffers.
While here, this removes an unimplemented check for detached array buffers when converting from ES values to IDL types, fixing #352.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/allowshared.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/9d039f6...67710b2.html)

Add [AllowShared] to allow accepting SharedArrayBuffers

---

index.bs

This was only ever implemented in Firefox. It was added in 5982ce7e323cffd7a673cb9af973c1c4f1e76fbe. after being removed as a result of https://www.w3.org/Bugs/Public/show_bug.cgi?id=12295.
Closes #129.
---
This ensures that authors can maintain the invariant they are used to where `x instanceof Y` means that `Y.prototype`'s methods are available on `x` (which is not true in Firefox). It also aligns with normal author-created or built-in ECMAScript objects, where e.g. `{} instanceof otherWindow.Object` returns false.
As pointed out in #129, only @travisleithead from a non-Firefox browser expressed support for the currently-specced behavior, and they have not implemented it in the intervening 4 years; Travis, I'd be curious if your team's feelings have changed. Chrome strongly objects to …

Remove custom [[HasInstance]] behavior from interface objects

---

index.bs

Closes #341.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/clarify-type-xattrs.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/d0899e9...2eaf4ca.html)

Clarify and add examples for "extended attributes associated with"

---

index.bs

This was not corrected as part of #286. Thanks @cdumez for spotting it!
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/fixup-xattr.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/d0899e9...c0485ed.html)

Fix [TreatNullAs] usage in example

---

index.bs

Fixes #362.
***
[Preview](https://s3.amazonaws.com/pr-preview/zcorpan/webidl/zcorpan/legacywindowalias.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/4dbd7d2...zcorpan:d346eb0.html)

Add [LegacyWindowAlias] extended attribute for WebKitCSSMatrix et al

---

index.bs

***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/frozen-array-json-type.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b323f1a...tobie:2db2816.html)

Add frozen array types to the list of JSON types

---

index.bs

This fixes #55. As discussed there, the definition of DOMException does not match any implementations. https://github.com/heycam/webidl/commit/137856d678f67b6f79f0c3ef4bd7d233629a685f exacerbated this, but it was already incorrect (e.g. defining own properties). Instead, implementations seem to implement DOMException as an interface with a small amount of custom bindings. This updates the specification to reflect that.
As part of this, it is no longer a distinct type, but instead an interface type.
---
Tests: https://github.com/w3c/web-platform-tests/issues/6361
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/fix-domexception.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/4269cc0...4dd161f.html)

Re-align DOMException objects with what is implemented

---

index.bs

Small changes to the documentation to fix some typos and grammar errors in some advisements.
***
[Preview](https://s3.amazonaws.com/pr-preview/lerouche/webidl/fix-typos.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/5c8eb31...lerouche:a7fb655.html)

Fix typos in advisements relating to using `true` as default values

---

index.bs

This is a fixup of 5c8eb310ef7a6bcb3c4813e9791212ee1624f2d3, which forgot to remove the DOMException terminal from the grammar when giving it a new definition.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/domexception-fixup.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f3b6a2a...25c1044.html)

Remove DOMException terminal from the grammar

---

index.bs

Make it explicit that the algorithm only accepts strings as input and does not throw.
Fixes #346.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-346.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b085536...tobie:9cc61a6.html)

Editorial: improve array index property name algorithm

---

index.bs

Fixes #280.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-280.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b085536...tobie:c49be36.html)

Link function objects to ES spec directly.

---

index.bs

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=23879.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25630.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-23879.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b085536...tobie:0940651.html)

Fix incorrect example in Overloading section.

---

index.bs

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=22888.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-22888.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b085536...tobie:de03523.html)

Editorial: improve language used around real numeric values.

---

index.bs

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29240.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-29240.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/5c1fce0...tobie:42db137.html)

Clarify that unrestricted doubles and floats include NaNs.

---

index.bs

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25628.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-25628.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/5c1fce0...tobie:42c6415.html)

Fix sentence that required optionality values to be boolean

---

index.bs

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25590.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-25590.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/b085536...tobie:6176810.html)

Clarify the effective overload set algorithm.

---

index.bs

Fixes part of https://www.w3.org/Bugs/Public/show_bug.cgi?id=27553. Fixes #301.
This will be necessary for https://github.com/whatwg/dom/pull/469, as feedback in https://github.com/whatwg/dom/issues/208 has been that we should restrict the type of the group to either a string or a symbol.
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27553 also contains speculative stuff about interfaces declaring their own symbols which is not included here.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/symbols.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/4269cc0...1ae927b.html)

Add the symbol type

---

index.bs

Fixes #400.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/legacy-keys.html#legacy-platform-object-ownpropertykeys) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/d6c3ddb...TimothyGu:ef6832d.html)

Define [[OwnPropertyKeys]] of legacy platform objects

---

index.bs

- Change <code>&lt;emu-val>*Type*&lt;/emu-val></code> where *Type* is one of the [fundamental ES language types](https://tc39.github.io/ecma262/#sec-ecmascript-language-types) to <code>*Type*</code>.
- Change <code>&lt;emu-val><var>Class</var>&lt;/emu-val></code> where *Class* is `Set`, `Map`, `SyntaxError`, or `Error` to <code>{{ECMAScript/<var>Class</var>}}</code> with appropriate links to ES spec.
- Change <code>&lt;emu-val><var>Exception</var>&lt;/emu-val></code> where *Exception* is one of the IDL simple exceptions to <code>{{<var>Exception</var>}}</code> with appropriate section links.
- Change `<emu-val>Function</emu-val>` to [function object](https://tc39.github.io/ecma262/#sec-ecmascript-function-objects), linked.
Fixes #404.
*** …

Use <emu-val> only for constant values

---

index.bs

Fixes #175.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/named-properties-symbol.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/8b83d25...TimothyGu:b0077c9.html)

Handle Symbols correctly in legacy platform object's [[DefineOwnProperty]]

---

index.bs

Closes #391.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-391.html#idl-overloading) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/c062489...tobie:b11cc67.html)

Use infra notation in Overloading section

---

index.bs

Fixes #102.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-102.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/fb40c8e...tobie:7ac2724.html)

Specify the property descriptor of @@unscopables.

---

index.bs

Closes #410.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-410.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/48f1e62...tobie:718ea3c.html)

Link function objects and constructors to relevant DFNs in ES

---

index.bs

Would be happy to update the class string once https://github.com/heycam/webidl/issues/419 is resolved, but submitting this for review first.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/values-to-iterate-over.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/48f1e62...TimothyGu:369c747.html)

Update SessionManager example

---

index.bs

Make advisements more prominent.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/link-legacy-apis.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/48f1e62...tobie:580c208.html)

Link legacy APIs within the advisements

---

index.bs

This sentence mistakenly suggested dictionaries could be annotated
with various extended attributes. When in fact they cannot.
Closes #422
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-422.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/080bcea...tobie:cf5c1a4.html)

Editorial: fix incorrect sentence about dictionaries

---

index.bs

This is necessary to specify certain APIs such as WebAssembly,
which includes several constructors as properties of the root
WebAssembly object. See a WebAssembly draft specification where
this is in use at https://github.com/littledan/spec/blob/new-js.bs/document/JS.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/littledan/webidl/namespace-interface.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f869be8...littledan:7f1899b.html)

Add [LegacyNamespace] to allow defining an interface in a namespace

---

index.bs

***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/fix-ref.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/93dc13d...b0e7199.html)

Editorial: correctly reference ES bindings section on constants

---

index.bs

Kept an explicit algorithm for determining if a property name is an array index as someone (forgot who) found it to be helpful.
Fixes #409.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/array-index.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f869be8...TimothyGu:4f5c681.html)

Link to ES for "array index"

---

index.bs

Closes #201.
***
[Preview](https://s3.amazonaws.com/pr-preview/heycam/webidl/tobie-OrdinarySetWithOwnDescriptor.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/931394e...2f447b5.html)

Meta: Use OrdinarySetWithOwnDescriptor

---

index.bs

For details, see the specific commits. The last commit ("Use abstract-op appropriately") was done mostly automatedly.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/update-es.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/d28583e...TimothyGu:20fddb6.html)

Various editorial updates related to ECMAScript

---

index.bs

Turns out there is only one interface in the Platform using legacy callers (`HTMLAllCollection`). Define the exotic behaviors there instead. PR for that is pending.
Fixes #407.
Fixes #408.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/legacycaller.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f97da39...TimothyGu:5ee55c8.html)

Remove legacy callers

---

index.bs

Fixes #307.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/overloads-vs-union-optional.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f869be8...TimothyGu:778d44d.html)

Add a section on overloads vs. union/optional

---

index.bs

***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-spelling.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/93f9ef0...tobie:bdd1a64.html)

Editorial: fix spelling mistakes

---

index.bs

***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/ecma.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/93f9ef0...TimothyGu:aa87708.html)

More ECMAScript biblio cleanup

---

.gitignore
.travis.yml
check-grammar.js
deploy.sh
index.bs
package.json

Fix existing conflicts.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/check-grammar.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/e99b578...tobie:eeba0a1.html)

Check grammar is LL(1) as part of Travis builds

---

index.bs

~~This is an early peek. Still a number of things to figure out, but though some of you would be interested to check it out already.~~
As I mentioned on IRC, I feel like the mental model I'm using for mixins is that they're named interface partials that can extend more than one interface with a limited set of members.
~~Not asking for a review right now, but high-level issues/comments welcomed.~~
***
Discussion happening at #363.
Follow-up issues at #450.
Still to do:
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/mixins.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/76c5192...tobie:8061293.html)

Add mixins

---

index.bs

Add a note on the difference of ECMAScript's SyntaxError and
"SyntaxError", which is one of the DOMException's names.
***
[Preview](https://s3.amazonaws.com/pr-preview/TakayoshiKochi/webidl/syntax_error.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/76c5192...TakayoshiKochi:358c37e.html)

Add a note on the difference of SyntaxError

---

index.bs

This algorithm applies to all function invocations, not
just those described in the spec as overloaded - see #461 for discussion.
***
[Preview](https://s3.amazonaws.com/pr-preview/timruffles/webidl/tr/specific.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/6673a82...timruffles:c3e0be1.html)

Fix #461 - clarify applicability of overload resolution

---

.pr-preview.json
Makefile
deploy.sh
index.bs
package.json

Now that the deploy-script relies on node.js to test the grammar, adding an extra-step to get rid of the dynamic generation of the IDL grammar index and formatting isn't that complicated.
This is split up in three commits: 
1. only uses post-processing for pr-preview (which makes it possible to have good HTML diffs of the grammar).
2. adds it to the deploy script, so the published spec no longer needs JS for content generation.
3. Adds-it to the Makefile (but defaults to dynamic generation if node isn't installed).
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/post-process.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/c3e67b3...tobie:d95debc.html)

Add post-processor

---

index.bs

This PR fixes [2.4.3. Operations](https://heycam.github.io/webidl/#idl-operations) which currently says:
>An operation is an interface member (matching static OperationRest, stringifier OperationRest, RegularOperation or SpecialOperation) that defines a behavior that can be invoked on objects implementing the interface.
In fact, both StaticMember and Stringifier requires RegularOperation:
https://heycam.github.io/webidl/#prod-StaticMember
```
StaticMember ::
static StaticMemberRest
StaticMemberRest ::
ReadOnly AttributeRest
RegularOperation
```
https://heycam.github.io/webidl/#prod-Stringifier
```
Stringifier ::
stringifier StringifierRest
StringifierRest ::
ReadOnly AttributeRest
RegularOperation
;
```
***
[Preview](https://s3.amazonaws.com/pr-preview/saschanaz/webidl/static-regular.html) …

static/stringifer RegularOperation

---

index.bs

This follows e2832d1fbff744f9a73658dbb9ac5b992be4c730.
***
[Preview](https://s3.amazonaws.com/pr-preview/saschanaz/webidl/emu-t-regex.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/95aeaf7...saschanaz:faffdcb.html)

Replace remaining emu-t.symbol

---

index.bs

Additionally:
- Annotate all interfaces in examples with [Exposed].
- Make [Global] allow a single identifier.
Fixes #365. 
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=26425.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-365.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/a578ac5...tobie:79a0f33.html)

Make [Exposed] mandatory, remove [PrimaryGlobal]

---

index.bs

The first commit changes the notation of strings within Web IDL to Infra-mandated "`string`". This helps prevent errors like #419 to exist in the first place, as it can be difficult to tell the difference between " Iterator" and "Iterator" without monospace styling.
The second commit fixes a Bikeshed linking error.
The third commit is a normative change that actually fixes #419, by incorporating the consensus reached in https://github.com/heycam/webidl/issues/419#issuecomment-323790991.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/483.html" title="Last updated on Dec 7, 2017, 11:40 AM GMT (c596cef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/483/2394cc9...TimothyGu:c596cef.html" title="Last updated on Dec 7, 2017, 11:40 AM GMT …

Add space to class string of iterator objects

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/464.html" title="Last updated on Dec 14, 2017, 5:57 PM GMT (6522a97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/464/90efe5b...tobie:6522a97.html" title="Last updated on Dec 14, 2017, 5:57 PM GMT (6522a97)">Diff</a>

Fix and clarify exposed dfn

---

index.bs

|F| is not defined until later. Use an equivalent check instead.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/500.html" title="Last updated on Dec 20, 2017, 4:35 AM GMT (0cc44fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/500/02e998a...TimothyGu:0cc44fd.html" title="Last updated on Dec 20, 2017, 4:35 AM GMT (0cc44fd)">Diff</a>

Editorial: Correct assertion

---

index.bs

Closes w3c/fxtf-drafts#233.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/502.html" title="Last updated on Dec 28, 2017, 11:35 PM GMT (7bce4f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/502/09d8f54...7bce4f1.html" title="Last updated on Dec 28, 2017, 11:35 PM GMT (7bce4f1)">Diff</a>

Editorial: add DOMRectList to the legacy [NoInterfaceObject] list

---

index.bs

Reverts heycam/webidl#502.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/503.html" title="Last updated on Dec 29, 2017, 1:20 PM GMT (c6febf0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/503/884623d...c6febf0.html" title="Last updated on Dec 29, 2017, 1:20 PM GMT (c6febf0)">Diff</a>

Editorial: Revert "add DOMRectList to the legacy [NoInterfaceObject] list"

---

index.bs

Closes #504.
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/505.html" title="Last updated on Jan 2, 2018, 11:04 PM GMT (9ec9589)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/505/f6d726e...tobie:9ec9589.html" title="Last updated on Jan 2, 2018, 11:04 PM GMT (9ec9589)">Diff</a>

Include typedefs in the JSON type definition

---

index.bs

I often see confusion about deprecation and legacy constructs. For example: https://github.com/KhronosGroup/WebGL/pull/2566#issuecomment-353656192. I was also very confused by this when I started working on WebIDL.
This is an attempt at clarifying this. I'm not sure whether all advisements should just link to this section, be completely replaced by a link to it, or should simply co-exist as in this current PR. Thoughts welcomed.
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/506.html" title="Last updated on Jan 4, 2018, 7:07 PM GMT (82550f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/506/d28856d...tobie:82550f5.html" title="Last updated on Jan 4, 2018, 7:07 PM GMT (82550f5)">Diff</a>

Add informative section on legacy constructs

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/508.html" title="Last updated on Jan 7, 2018, 12:27 PM GMT (77b6fa2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/508/1244c86...tobie:77b6fa2.html" title="Last updated on Jan 7, 2018, 12:27 PM GMT (77b6fa2)">Diff</a>

Editorial: remove the remaining subscript notation for argument lists

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/513.html" title="Last updated on Jan 19, 2018, 1:17 PM GMT (8f59989)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/513/5f2b156...tobie:8f59989.html" title="Last updated on Jan 19, 2018, 1:17 PM GMT (8f59989)">Diff</a>

Specify PropertyDescriptor of @@toStringTag symbol

---

index.bs

Now that [`legacycaller` is gone](https://github.com/heycam/webidl/issues/408)
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/webidl/pull/519.html" title="Last updated on Feb 8, 2018, 3:46 PM GMT (4c6c5fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/519/41bc728...dontcallmedom:4c6c5fe.html" title="Last updated on Feb 8, 2018, 3:46 PM GMT (4c6c5fe)">Diff</a>

Four (not five) kind of special operations

---

index.bs

Per consensus reached in #483, class strings should only exist on iterator prototype objects.
Tests: https://github.com/w3c/web-platform-tests/pull/8796
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/501.html" title="Last updated on Dec 25, 2017, 2:09 AM GMT (513317f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/501/02e998a...TimothyGu:513317f.html" title="Last updated on Dec 25, 2017, 2:09 AM GMT (513317f)">Diff</a>

Remove definition of class strings of default iterator objects

---

index.bs

"declaration" was linked to the definition in [CSS-SYNTAX-3].
Use/fix Bikeshed autolinking.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/538.html" title="Last updated on Mar 24, 2018, 7:10 PM GMT (f317fc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/538/3ef2ba7...TimothyGu:f317fc8.html" title="Last updated on Mar 24, 2018, 7:10 PM GMT (f317fc8)">Diff</a>

Editorial: minor copy editing

---

README.md

Follows https://github.com/heycam/webidl/issues/543.

Meta: remove label info from README

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/549.html" title="Last updated on Apr 19, 2018, 9:30 PM GMT (d19974d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/549/121edc5...tobie:d19974d.html" title="Last updated on Apr 19, 2018, 9:30 PM GMT (d19974d)">Diff</a>

Editorial: use SetFunctionLength abstract ops

---

index.bs

As of:
https://github.com/w3c/csswg-drafts/commit/b05eb1b9c05c22f771aff6a3ae7cdbb4a925522e
The spec references to [LegacyArrayClass] are gone from CSSOM.
See https://github.com/w3c/csswg-drafts/issues/2601.
***
<a href="https://pr-preview.s3.amazonaws.com/emilio/webidl/pull/550.html" title="Last updated on Apr 24, 2018, 5:13 AM GMT (f5667f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/550/aecffc4...emilio:f5667f1.html" title="Last updated on Apr 24, 2018, 5:13 AM GMT (f5667f1)">Diff</a>

[LegacyArrayClass] is gone from CSSOM.

---

index.bs

Nothing in the web platform uses it anymore.
Fixes #291.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/551.html" title="Last updated on Apr 27, 2018, 9:08 AM GMT (4cb4671)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/551/fb70995...4cb4671.html" title="Last updated on Apr 27, 2018, 9:08 AM GMT (4cb4671)">Diff</a>

Remove [LegacyArrayClass]

---

index.bs

In the section of `[LenientSetter]`, a sentence commented on `[LenientThis]` by mistake.

Fix a wrong description `[LenientThis]`

---

index.bs

The confusion between _V_ and _value_ caused myself, @domfarolino, and @TimothyGu many minutes of confusion before @bzbarsky straightened things out.

Editorial: use less-confusing variable names in dictionary conversion

---

index.bs

Closes #470 
This was to allow `setter creator` but is not useful anymore.

Disallow multiple keywords for SpecialOperation

---

index.bs

Fixes https://github.com/heycam/webidl/issues/555
***
<a href="https://pr-preview.s3.amazonaws.com/bzbarsky/webidl/pull/571.html" title="Last updated on Jul 16, 2018, 11:31 PM GMT (ec1f2c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/571/ebdaa2b...bzbarsky:ec1f2c9.html" title="Last updated on Jul 16, 2018, 11:31 PM GMT (ec1f2c9)">Diff</a>

A dictionary inheriting from a non-JSON type can't be a JSON type.

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/577.html" title="Last updated on Sep 20, 2018, 8:59 AM GMT (4ad138f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/577/4afb5e8...Ms2ger:4ad138f.html" title="Last updated on Sep 20, 2018, 8:59 AM GMT (4ad138f)">Diff</a>

Include the legacy namespace identifier in both interface prototype objects and platform objects.

---

index.bs

"Additionally" was spelt "additionaly" in a number of places. Fix it.
***
<a href="https://pr-preview.s3.amazonaws.com/ricea/webidl/pull/590.html" title="Last updated on Nov 30, 2018, 6:41 AM GMT (9c3bcf9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/590/b0aa0b7...ricea:9c3bcf9.html" title="Last updated on Nov 30, 2018, 6:41 AM GMT (9c3bcf9)">Diff</a>

Correct the spelling of "additionally"

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/sideshowbarker/webidl/pull/593.html" title="Last updated on Dec 7, 2018, 11:17 AM GMT (d6cbaf3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/593/822328f...sideshowbarker:d6cbaf3.html" title="Last updated on Dec 7, 2018, 11:17 AM GMT (d6cbaf3)">Diff</a>

Fix typo in example in Namespaces section

---

index.bs

Fixing a typo introduced in #494
cc @tobie
***
<a href="https://pr-preview.s3.amazonaws.com/littledan/webidl/pull/596.html" title="Last updated on Dec 10, 2018, 7:16 AM GMT (e94abc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/596/5a20e34...littledan:e94abc8.html" title="Last updated on Dec 10, 2018, 7:16 AM GMT (e94abc8)">Diff</a>

Only [Global] platform objects are immutable prototype

---

index.bs

As far as I can tell there's no way for a %TypedArray%'s [[ViewedArrayBuffer]] internal slot to be undefined. I'm pretty sure this has to be the case as implementations assume this algorithm to never throw (the detached issue is tracked separately by #151).
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/604.html" title="Last updated on Jan 9, 2019, 2:44 PM UTC (3391298)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/604/8f48c5a...3391298.html" title="Last updated on Jan 9, 2019, 2:44 PM UTC (3391298)">Diff</a>

[[ViewedArrayBuffer]] cannot be undefined during usage

---

index.bs

Instead treat them the same as the empty byte sequence as implementations have been doing since forever.
This also performs the IsDetachedBuffer abstract operation on the correct object.
Fixes #151.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/605.html" title="Last updated on Jan 10, 2019, 8:57 AM UTC (19fa3e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/605/8f48c5a...19fa3e2.html" title="Last updated on Jan 10, 2019, 8:57 AM UTC (19fa3e2)">Diff</a>

Detached ArrayBuffer objects should not throw

---

index.bs

Fixes #583.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/611.html" title="Last updated on Jan 15, 2019, 10:27 AM UTC (e79feeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/611/d05c8cc...Ms2ger:e79feeb.html" title="Last updated on Jan 15, 2019, 10:27 AM UTC (e79feeb)">Diff</a>

Use %PromiseProto_then% to 'perform some steps once a promise is settled'.

---

index.bs

Fixes #542.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/617.html" title="Last updated on Jan 16, 2019, 9:47 AM UTC (54c60d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/617/d05c8cc...Ms2ger:54c60d1.html" title="Last updated on Jan 16, 2019, 9:47 AM UTC (54c60d1)">Diff</a>

Editorial: Remove section numbers from ES references.

---

index.bs

This PR fixes the following sentence:
```diff
- The inner type must not be […] a union type that itself has includes a nullable type 
+ The inner type must not be […] a union type that itself includes a nullable type 
```
cf. section https://heycam.github.io/webidl/#idl-nullable-type
***
<a href="https://pr-preview.s3.amazonaws.com/vhf/webidl/pull/628.html" title="Last updated on Jan 21, 2019, 2:59 PM UTC (339f954)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/628/45438a1...vhf:339f954.html" title="Last updated on Jan 21, 2019, 2:59 PM UTC (339f954)">Diff</a>

Editorial: fix language in nullable types section

---

index.bs

This should prevent confusion between the production and the keyword. Fixes #558.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/616.html" title="Last updated on Jan 28, 2019, 1:31 PM UTC (c04bd6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/616/d05c8cc...Ms2ger:c04bd6a.html" title="Last updated on Jan 28, 2019, 1:31 PM UTC (c04bd6a)">Diff</a>

Rename the 'float' production to 'real'.

---

index.bs

It seems like a bad idea to allow [Global] on a partial interface.
The behavior of [Exposed] and [SecureContext] on partial interfaces is already
defined in the relevant algorithms.
The behavior of [OverrideBuiltins] is defined here with the same vague wording
used before. It might be better to disentangle the concept of an interface and
its syntactical structure.
Fixes #154.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/620.html" title="Last updated on Jan 16, 2019, 1:12 PM UTC (c0d8b12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/620/ce7b02c...Ms2ger:c0d8b12.html" title="Last updated on Jan 16, 2019, 1:12 PM UTC (c0d8b12)">Diff</a>

Restrict the extended attributes for partial interfaces.

---

index.bs

Fixes #564.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/612.html" title="Last updated on Jan 15, 2019, 10:59 AM UTC (ed1765c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/612/d05c8cc...Ms2ger:ed1765c.html" title="Last updated on Jan 15, 2019, 10:59 AM UTC (ed1765c)">Diff</a>

Allow identifiers that start with a hyphen.

---

index.bs

This was a bit confusing to me when reading the definition of operations
and attributes in the ECMAScript binding--there is a link from that definition to
"member", but no explicit definition of which members are included there (you
have to go check the definition of interface mixin).
***
<a href="https://pr-preview.s3.amazonaws.com/littledan/webidl/pull/594.html" title="Last updated on Jan 28, 2019, 10:28 PM UTC (860e1c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/594/5a20e34...littledan:860e1c6.html" title="Last updated on Jan 28, 2019, 10:28 PM UTC (860e1c6)">Diff</a>

Editorial: Note that interface mixins' elements are included among interface elements

---

index.bs

Fixes #141.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/621.html" title="Last updated on Jan 30, 2019, 9:09 AM UTC (cfd45ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/621/ce7b02c...Ms2ger:cfd45ff.html" title="Last updated on Jan 30, 2019, 9:09 AM UTC (cfd45ff)">Diff</a>

Clarify the interpretation of string literal tokens.

---

index.bs

Running the named property visibility algorithm is (or should be) observable
by inserting a proxy in the prototype chain. This changes the spec to match
Gecko's behavior.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/625.html" title="Last updated on Jan 31, 2019, 8:21 AM UTC (4f60f42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/625/45438a1...Ms2ger:4f60f42.html" title="Last updated on Jan 31, 2019, 8:21 AM UTC (4f60f42)">Diff</a>

Check ignoreNamedProps before the named property visibility algorithm.

---

index.bs

Fixes #119.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/637.html" title="Last updated on Feb 5, 2019, 10:07 AM UTC (be59c93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/637/f733024...be59c93.html" title="Last updated on Feb 5, 2019, 10:07 AM UTC (be59c93)">Diff</a>

Add cross-reference to 'exposed' in the [SecureContext] definition

---

index.bs

The specification required defining the operations and attributes for the Global
interface itself as well as its inherited interfaces on the object itself.
This is not implemented in Gecko, Chrome or WebKit: none of these engines
defines, for example, the `addEventListener` method on the window object.
I suspect this text was meant to refer to mixin interfaces rather than
inherited interfaces, but these are already covered by a catch-all statement.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/639.html" title="Last updated on Feb 6, 2019, 4:05 PM UTC (db1a9fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/639/fa21124...db1a9fc.html" title="Last updated on Feb 6, 2019, 4:05 PM UTC (db1a9fc)">Diff</a>

Correct requirement to define Global properties on the object itself

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/635.html" title="Last updated on Feb 22, 2019, 2:01 PM UTC (976b7ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/635/7769c5f...976b7ff.html" title="Last updated on Feb 22, 2019, 2:01 PM UTC (976b7ff)">Diff</a>

Add an algorithm to create a platform object.

---

index.bs

This doesn't currently happen, and we don't expect it to happen in the future.
Fixes #645.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/651.html" title="Last updated on Feb 25, 2019, 11:18 AM UTC (5da20cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/651/4d049be...5da20cf.html" title="Last updated on Feb 25, 2019, 11:18 AM UTC (5da20cf)">Diff</a>

Disallow combining LegacyWindowAlias and LegacyNamespace

---

index.bs

This matches the text for normal constructors. I forgot to update this
algorithm in 8e1b52942525e9135885eba8aa68c028d2c6a5be.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/652.html" title="Last updated on Feb 25, 2019, 1:59 PM UTC (593fe84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/652/4d049be...593fe84.html" title="Last updated on Feb 25, 2019, 1:59 PM UTC (593fe84)">Diff</a>

Clarify object creation in named constructors

---

index.bs

Fixes #512.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/640.html" title="Last updated on Feb 9, 2019, 2:25 AM UTC (a6b9638)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/640/fc5da8f...TimothyGu:a6b9638.html" title="Last updated on Feb 9, 2019, 2:25 AM UTC (a6b9638)">Diff</a>

Specify what typeof should return for exotic objects

---

index.bs

- Update the steps for instantiating a platform object, which everything
theoretically calls into, and which sets the primary interface into a new
internal slot [[PrimaryInterface]].
- Define the "implements" algorithm as checking the [[PrimaryInterface]]
internal slot.
The algorithm here is roughly in correspondence with the V8 implementation,
where operation functions are allocated with a reference to a
FunctionTemplate object (which is in corresondence with WebIDL interfaces).
When checking the receiver of a method that came from WebIDL, the original
prototype chain is traversed by looking at the FunctionTemplate's parent.
The same FunctionTemplate is used in multiple JavaScript realms.
Fixes #97.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/654.html" title="Last …

Define "implements" checks using internal slots

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/648.html" title="Last updated on Feb 25, 2019, 4:38 PM UTC (752f29b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/648/d534bbe...752f29b.html" title="Last updated on Feb 25, 2019, 4:38 PM UTC (752f29b)">Diff</a>

Imperatively define the global property references

---

index.bs

Note that this slot was already used in assertions for the result of the
[Constructor] and [NamedConstructor] implementation algorithms.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=24652.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/658.html" title="Last updated on Feb 25, 2019, 4:47 PM UTC (7f9d3c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/658/d534bbe...7f9d3c4.html" title="Last updated on Feb 25, 2019, 4:47 PM UTC (7f9d3c4)">Diff</a>

Formally define a [[Realm]] slot on platform objects

---

index.bs

The spec already requires:
> Interfaces that support indexed properties must define an integer-typed
> attribute named length.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/667.html" title="Last updated on Feb 28, 2019, 2:06 PM UTC (a765ae3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/667/c705ce6...a765ae3.html" title="Last updated on Feb 28, 2019, 2:06 PM UTC (a765ae3)">Diff</a>

Editorial: remove redundant requirement for existence of 'length'

---

index.bs

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25050.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=26767.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/673.html" title="Last updated on Mar 1, 2019, 1:35 PM UTC (3608f4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/673/c705ce6...3608f4c.html" title="Last updated on Mar 1, 2019, 1:35 PM UTC (3608f4c)">Diff</a>

Clarify note about enum conversion exceptions

---

index.bs

This prose is converting IDL values to JS values, so they should not try to
convert to IDL types.
Separately, fix some grammar nits.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=20455.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/664.html" title="Last updated on Mar 1, 2019, 4:28 PM UTC (e325ade)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/664/c705ce6...e325ade.html" title="Last updated on Mar 1, 2019, 4:28 PM UTC (e325ade)">Diff</a>

Editorial: improve language around conversions to JS

---

index.bs

Platform objects can be used as callback interfaces in all browsers, so there's
no point in having this distinction.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/662.html" title="Last updated on Feb 26, 2019, 4:50 PM UTC (4d27f0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/662/c705ce6...4d27f0c.html" title="Last updated on Feb 26, 2019, 4:50 PM UTC (4d27f0c)">Diff</a>

Remove the 'user object' concept.

---

index.bs

This avoids the ambiguity around which `@@iterator` to use. This combination is
not currently used; if a use case comes up, we can reconsider this.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28592.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/671.html" title="Last updated on Mar 4, 2019, 12:15 PM UTC (95ad6ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/671/c705ce6...95ad6ba.html" title="Last updated on Mar 4, 2019, 12:15 PM UTC (95ad6ba)">Diff</a>

Disallow combining an indexed getter with a maplike/setlike

---

index.bs

This avoids creating a new function object for every instance.
This change is already implemented in Gecko and Chromium.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28739.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/668.html" title="Last updated on Mar 1, 2019, 1:06 PM UTC (582d788)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/668/c705ce6...582d788.html" title="Last updated on Mar 1, 2019, 1:06 PM UTC (582d788)">Diff</a>

Deduplicate unforgeable member functions

---

index.bs

The prose about 'initial objects' can probably be removed with a little
more work, now that object creation is imperative.
The paragraph about exposing interfaces is no longer particularly useful
since the Exposed extended attribute is required.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/681.html" title="Last updated on Mar 8, 2019, 8:28 AM UTC (834c103)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/681/a94e4b4...834c103.html" title="Last updated on Mar 8, 2019, 8:28 AM UTC (834c103)">Diff</a>

Remove references to ECMAScript global environments

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/679.html" title="Last updated on Mar 7, 2019, 2:23 PM UTC (b549ba8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/679/a94e4b4...b549ba8.html" title="Last updated on Mar 7, 2019, 2:23 PM UTC (b549ba8)">Diff</a>

Correct the 'indexed getter' cross-reference

---

index.bs

Currently we technically pass around JS objects to specifications
that use IDL to define their APIs.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/666.html" title="Last updated on Mar 14, 2019, 2:59 PM UTC (3cfbccf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/666/ff2b414...3cfbccf.html" title="Last updated on Mar 14, 2019, 2:59 PM UTC (3cfbccf)">Diff</a>

Editorial: run platform algorithms on IDL objects

---

index.bs

Closes #448.
No known specs are using constant null, and we discourage adding new constants (with some specs as exceptions), so I think we can safely remove this.
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/webidl/pull/686.html" title="Last updated on Mar 11, 2019, 11:02 AM UTC (6094723)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/686/cc2fa40...saschanaz:6094723.html" title="Last updated on Mar 11, 2019, 11:02 AM UTC (6094723)">Diff</a>

Disallow constants to be null

---

index.bs

We use the interface object of the inherited interface in the 'create an
interface object' algorithm, so this ensures it already exists at that point.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/682.html" title="Last updated on Mar 8, 2019, 5:02 PM UTC (73e145a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/682/b4f9467...73e145a.html" title="Last updated on Mar 8, 2019, 5:02 PM UTC (73e145a)">Diff</a>

Ensure that interface objects aren't used before they exist

---

check-grammar.js
deploy.sh

In particular, fail immediately if the server returns with an error, and yield
a readable error if no grammar snippets are found in the specification.

Make the grammar check more robust

---

index.bs

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=27301.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/665.html" title="Last updated on Mar 18, 2019, 10:09 AM UTC (95b778a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/665/6dcfbec...95b778a.html" title="Last updated on Mar 18, 2019, 10:09 AM UTC (95b778a)">Diff</a>

Formalize the 'this' and 'given value' ambient values

---

index.bs

This was only supported in the definition of the effective overload set, but
this wasn't actually used anywhere, and there is no syntax to overload a
callback anyway.
The six types of IDL constructs are the five that were in the specification
before this change, and legacycallers. The count was not updated when these
were removed.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/690.html" title="Last updated on Mar 19, 2019, 10:21 AM UTC (404e94f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/690/b0621a8...404e94f.html" title="Last updated on Mar 19, 2019, 10:21 AM UTC (404e94f)">Diff</a>

Remove support for overloading callbacks

---

index.bs

I didn't notice this paragraph in 8e1b52942525e9135885eba8aa68c028d2c6a5be,
where it should have been updated.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/697.html" title="Last updated on Mar 26, 2019, 2:38 PM UTC (21c1a17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/697/b47c90c...21c1a17.html" title="Last updated on Mar 26, 2019, 2:38 PM UTC (21c1a17)">Diff</a>

Update the requirement about the definition of a constructor

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/699.html" title="Last updated on Mar 29, 2019, 11:16 AM UTC (e0a3316)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/699/b47c90c...e0a3316.html" title="Last updated on Mar 29, 2019, 11:16 AM UTC (e0a3316)">Diff</a>

Correct the effective overload set use for named constructors

---

index.bs

We do not allow read-only attributes to be annotated with it, so we might as
well prevent it in the grammar. This is already done for static attributes.
Fixes #703.

Tighten the grammar for the 'inherit' keyword

---

index.bs

PartialInterfaceRest does not include the 'interface' keyword.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/693.html" title="Last updated on Mar 20, 2019, 3:32 PM UTC (ce45f11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/693/b0621a8...ce45f11.html" title="Last updated on Mar 20, 2019, 3:32 PM UTC (ce45f11)">Diff</a>

Fix a grammar mistake in the 'partial interface' definition

---

index.bs

Annotated types lists 3 extended attributes as applicable-to-type attributes, and [AllowShared] is not in the list.
On the other hand, [AllowShared] is explained to appear on one of the buffer source type, and it means [AllowShared] is applicable to types.
This PR adds [AllowShared] in the list of applicable to types extended attributes, so that it fixes the ambiguity.
Fixes #687.
***
<a href="https://pr-preview.s3.amazonaws.com/peria/webidl/pull/695.html" title="Last updated on Apr 4, 2019, 8:12 AM UTC (5e8329e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/695/b47c90c...peria:5e8329e.html" title="Last updated on Apr 4, 2019, 8:12 AM UTC (5e8329e)">Diff</a>

Add [AllowShared] in the list of applicable-to-types

---

index.bs

See https://github.com/tc39/ecma262/pull/1441.
This therefore reverts 5de45d9bc817fb0ce3f498e4ca9c14adbee2d172.

JavaScript defines typeof fully now

---

index.bs

Array index properties are not special on objects with named setters. Note
that the corresponding step in [[DefineOwnProperty]] does not have this
condition.
This change does not affect normal usage; it is only detectable by messing with
the prototype of the object.
Gecko and WebKit already handle array indexes the same way as other properties;
Chrome does for DOMStringMap but does not for Storage. (In the Storage case, it
does the exact opposite of the current specification.)
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/706.html" title="Last updated on Apr 4, 2019, 2:58 PM UTC (53097fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/706/0b75c48...53097fb.html" title="Last updated on Apr 4, 2019, 2:58 PM UTC (53097fb)">Diff</a>

Remove a check for array index in [[Set]]

---

index.bs

Callback interfaces and interfaces have very little in common, so this makes
them separate concepts. It doesn't change the name or syntax to avoid
unhelpful churn.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/705.html" title="Last updated on Apr 4, 2019, 1:48 PM UTC (c373a0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/705/0b75c48...c373a0e.html" title="Last updated on Apr 4, 2019, 1:48 PM UTC (c373a0e)">Diff</a>

Stop claiming callback interfaces are interfaces

---

index.bs

An interface can only have a (named or indexed) setter if it also has the
corresponding getter, so checking for both is unnecessary.

Editorial: Shorten the conditions in the [[Set]] algorithm

---

index.bs

This seems to be broken in bikshed.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/721.html" title="Last updated on May 7, 2019, 1:54 PM UTC (fce7187)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/721/059491b...fce7187.html" title="Last updated on May 7, 2019, 1:54 PM UTC (fce7187)">Diff</a>

Editorial: Stop using markdown for bold

---

index.bs

Fixes #723.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/725.html" title="Last updated on May 10, 2019, 7:54 AM UTC (477bd48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/725/059491b...477bd48.html" title="Last updated on May 10, 2019, 7:54 AM UTC (477bd48)">Diff</a>

Editorial: Add min-width to distinguishable-table's cells

---

index.bs

Based on text written by Domenic at
<https://github.com/tc39/proposal-javascript-standard-library/pull/44>.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/722.html" title="Last updated on May 9, 2019, 3:20 PM UTC (2e6b8d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/722/059491b...2e6b8d0.html" title="Last updated on May 9, 2019, 3:20 PM UTC (2e6b8d0)">Diff</a>

Define Synthetic Module Records

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/728.html" title="Last updated on May 20, 2019, 7:48 AM UTC (fc82701)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/728/41e0d1e...fc82701.html" title="Last updated on May 20, 2019, 7:48 AM UTC (fc82701)">Diff</a>

Remove the Error IDL type

---

index.bs

The signature changed from (obj, method) to (obj, hint, method) when @@asyncIterator was introduced. Because the method is already known to be defined at this point, I don’t believe the hint argument will actually be used, but the argument still seems to be needed to put the method arg in the right position.
I was unsure what formatting "sync" should get here. It’s a constant symbolic value rather than a variable or a string. I didn’t see any pre-existing examples in the IDL spec, so it may need additional markup.
***
<a href="https://pr-preview.s3.amazonaws.com/bathos/webidl/pull/731.html" title="Last updated on May 29, 2019, 10:04 AM UTC (14536c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/731/4ef3509...bathos:14536c1.html" title="Last updated on May 29, …

The GetIterator operation in ECMA262 now takes three arguments

---

index.bs

Fixes #744.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/745.html" title="Last updated on Jun 27, 2019, 12:11 PM UTC (a9537fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/745/c0d927a...a9537fb.html" title="Last updated on Jun 27, 2019, 12:11 PM UTC (a9537fb)">Diff</a>

Disallow combining Global with Constructor/NamedConstructor.

---

index.bs

I accidentally missed a letter in #705.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/753.html" title="Last updated on Jul 1, 2019, 1:16 PM UTC (fc0ce5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/753/a029460...fc0ce5f.html" title="Last updated on Jul 1, 2019, 1:16 PM UTC (fc0ce5f)">Diff</a>

Fix the grammar for CallbackInterfaceMembers.

---

index.bs

Mark DOMException as serialiable
Also define serialization and deserialization steps.
tests: https://github.com/web-platform-tests/wpt/pull/17095
Fixes #729
***
<a href="https://pr-preview.s3.amazonaws.com/yutakahirano/webidl/pull/732.html" title="Last updated on Jun 7, 2019, 7:51 AM UTC (0017a1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/732/4ef3509...yutakahirano:0017a1d.html" title="Last updated on Jun 7, 2019, 7:51 AM UTC (0017a1d)">Diff</a>

Mark DOMException as serializable

---

index.bs

I'd like to refer to the WebIDL examples as the de facto style guide for WebIDL.
To that end, I'd like to fix an inconsistency in one example's use of `[]` that I found. From:
```js
[
Exposed=(Window,Worker),
Constructor(optional DOMString message = "", optional DOMString name = "Error"),
Serializable
]
interface DOMException {
```
to
```js
[Exposed=(Window,Worker),
Constructor(optional DOMString message = "", optional DOMString name = "Error"),
Serializable]
interface DOMException {
```
The latter appears to be the predominant style in this document as well as in [HTML](https://html.spec.whatwg.org/#htmlallcollection) and [DOM](https://dom.spec.whatwg.org/#interface-event).
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webidl/pull/759.html" title="Last updated on Jul 17, …

Fix one inconsistent use of [] in examples (editorial)

---

index.bs

Clarify the restrictions on SecureContext combinations.

---

index.bs

In particular, this acknowledges that `Promise<void>` exists.
This also ensures that the handling of `void` return types is defined fully.
Fixes #737.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/757.html" title="Last updated on Jul 2, 2019, 1:47 PM UTC (bb451af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/757/15563ce...bb451af.html" title="Last updated on Jul 2, 2019, 1:47 PM UTC (bb451af)">Diff</a>

Improve the definition of the void type.

---

index.bs

Fixes #580.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/720.html" title="Last updated on Aug 7, 2019, 10:20 AM UTC (6ac2d3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/720/13c7e8f...6ac2d3d.html" title="Last updated on Aug 7, 2019, 10:20 AM UTC (6ac2d3d)">Diff</a>

Add async_iterable support

---

index.bs

Fixes #752.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/766.html" title="Last updated on Aug 7, 2019, 8:36 AM UTC (c8b7848)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/766/13c7e8f...c8b7848.html" title="Last updated on Aug 7, 2019, 8:36 AM UTC (c8b7848)">Diff</a>

Editorial: Don't use ReadWriteMapLike/ReadWriteSetLike after 'readonly'.

---

index.bs

Closes #767 
Closes #768
Fixes https://github.com/whatwg/xhr/issues/251
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/webidl/pull/769.html" title="Last updated on Aug 14, 2019, 3:42 AM UTC (68aa41d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/769/a08d398...saschanaz:68aa41d.html" title="Last updated on Aug 14, 2019, 3:42 AM UTC (68aa41d)">Diff</a>

Allow `async` and `includes` as member names

---

index.bs

Fixes #636.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/700.html" title="Last updated on Aug 27, 2019, 2:00 PM UTC (dba5577)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/700/68dbd23...dba5577.html" title="Last updated on Aug 27, 2019, 2:00 PM UTC (dba5577)">Diff</a>

Stop using extended attributes for constructors

---

index.bs

See https://github.com/heycam/webidl/issues/778.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 29, 2019, 9:04 AM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fheycam%2Fwebidl%2F035c1568f6e19d1f2386b91492b9b8cc8318c1cf%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
WARNING: Multiple elements have the same ID 'w3c_process_revision'.
Deduping, but this ID may …
```

Use new syntax for DOMException.

---

index.bs

Ref. #142.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/775.html" title="Last updated on Aug 23, 2019, 2:51 PM UTC (b3450e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/775/34ef605...b3450e1.html" title="Last updated on Aug 23, 2019, 2:51 PM UTC (b3450e1)">Diff</a>

Editorial: Add an example of using ordered map syntax for dictionaries.

---

index.bs

Fixes #779
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 2, 2019, 9:00 AM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsaschanaz%2Fwebidl%2F390a9dc01dc40b262f50c7972b03a3e161c5e3e8%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
WARNING: Multiple elements have the same ID 'w3c_process_revision'.
Deduping, but this ID may not be stable across revisions. …
```

Allow "constructor" as an argument name

---

index.bs

Reverts heycam/webidl#780 for now until the tooling is ready.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 29, 2019, 3:25 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fheycam%2Fwebidl%2F21ffd9bd979bbebc99d1b7ed28c4f56b7c02b018%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
WARNING: Multiple elements have the same ID 'w3c_process_revision'.
Deduping, but …
```

Revert "Use new syntax for DOMException."

---

index.bs

Fixes #788.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/790.html" title="Last updated on Sep 4, 2019, 8:02 AM UTC (bd8283f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/790/182b487...bd8283f.html" title="Last updated on Sep 4, 2019, 8:02 AM UTC (bd8283f)">Diff</a>

Fix example for 'upon settling'.

---

index.bs

Closes #783.
/cc @jakearchibald
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/792.html" title="Last updated on Sep 3, 2019, 7:36 PM UTC (1f89230)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/792/182b487...1f89230.html" title="Last updated on Sep 3, 2019, 7:36 PM UTC (1f89230)">Diff</a>

Use "react" for the spec promise.then() analog

---

index.bs

This removes [Constructor] from DOMException and from examples, replacing
it as necessary with constructor operations.
***
<a href="https://pr-preview.s3.amazonaws.com/clelland/webidl/pull/798.html" title="Last updated on Sep 23, 2019, 2:42 PM UTC (2a37a9b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/798/db74ef4...clelland:2a37a9b.html" title="Last updated on Sep 23, 2019, 2:42 PM UTC (2a37a9b)">Diff</a>

Remove use of [Constructor] extended attribute

---

index.bs

This is for use in [HTMLConstructor] in https://github.com/whatwg/html/pull/4915.
There are alternative approaches and wordings that might be better, e.g.
- Say "perform the following steps or any others specified by specs" inline instead of allowing the usual steps to be replaced using a paragraph at the bottom
- Have an explicit "overridden constructor steps" value for each interface object, which [HTMLConstructor] sets and this algorithm consults
But I thought I'd start here to get the ball rolling, as it's the first thing that occurred to me. Happy to tweak as desired.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/797.html" title="Last updated on Sep 18, 2019, 8:36 AM UTC (4554894)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/797/db74e …

Define "usual constructor steps"

---

Makefile

At least on Windows with Git Bash, this is necessary.

Meta: fix Makefile escaping in fallback case

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/806.html" title="Last updated on Sep 26, 2019, 5:46 AM UTC (5604396)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/806/8450ca2...TimothyGu:5604396.html" title="Last updated on Sep 26, 2019, 5:46 AM UTC (5604396)">Diff</a>

Fix "overriden" typo

---

Makefile
index.bs

* Make builds fail on Bikeshed warnings, and display them, instead of silently proceeding.
* Remove duplicate w3c_process_revision ID to work around https://github.com/tabatkins/bikeshed/issues/1503.
* Depend on Infra explicitly to get some conformance stuff, instead of saying it again here. This removes the un-exported "processing equivalence" definition.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/807.html" title="Last updated on Sep 27, 2019, 6:22 AM UTC (bc17c83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/807/3f89daf...bc17c83.html" title="Last updated on Sep 27, 2019, 6:22 AM UTC (bc17c83)">Diff</a>

Meta: fix and prevent Bikeshed warnings

---

index.bs

I’m not confident that this attempted correction is quite right, but I figured one way to find out is to open a PR.
I think there might be another, unrelated issue in this definition. Later text implies that callback functions are also possible callable values, which don’t seem to be accounted for here.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 9, 2019, 12:57 AM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubu …

Overload set tuple: callable definition out of sync with new constructor ops

---

index.bs

Make both the "async iterator initialization steps" and the "get the next iteration result" take two arguments: the instance, and the async iterator. This ends up being more ergonomic than using the "current state" concept.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/802.html" title="Last updated on Oct 16, 2019, 10:54 AM UTC (2d6954b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/802/3f89daf...2d6954b.html" title="Last updated on Oct 16, 2019, 10:54 AM UTC (2d6954b)">Diff</a>

Tweak async iterator algorithms

---

index.bs

Closes #804. Notably this allows consumers to not worry about resolving their promise with the correct iterator result.
This is on top of the stage-setting commits in #802; only the last commit is worth reviewing.
One choice I made here where the right answer wasn't immediately obvious is that calling return() while a call to next() is outstanding will reject with no side effects. This mirrors what we've done in the Streams design, and seems simpler than e.g. waiting for 1+ outstanding next()s to settle. This will only occur when manually manipulating the async iterator (as opposed to using for-await-of) so it's not a very mainline scenario. /cc @ricea in case he has any thoughts.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/805.html" title="Last updated on Oct 16, …

Allow async iterators to specify return algorithms

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/822.html" title="Last updated on Nov 13, 2019, 4:10 PM UTC (7d9f364)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/822/5e51b73...7d9f364.html" title="Last updated on Nov 13, 2019, 4:10 PM UTC (7d9f364)">Diff</a>

Correct non-normative summary of the overload resolution algorithm.

---

index.bs

The&nbsp;definition of&nbsp;`callback interface` lists&nbsp;[`EventListener`](https://dom.spec.whatwg.org/#callbackdef-eventlistener) as&nbsp;what needs&nbsp;it for&nbsp;legacy&nbsp;reasons.
This&nbsp;makes it&nbsp;into a&nbsp;reference, like&nbsp;what&nbsp;other legacy&nbsp;**WebIDL**&nbsp;features do&nbsp;with&nbsp;definitions that&nbsp;need&nbsp;them.
***
<a href="https://pr-preview.s3.amazonaws.com/EB-Forks/webidl/pull/826.html" title="Last updated on Dec 12, 2019, 12:58 AM UTC (2119792)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/826/513c5ea...EB-Forks:2119792.html" title="Last updated on Dec 12, 2019, 12:58 AM UTC (2119792)">Diff</a>

docs(`callback interface`): Make `EventListener` into reference

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/shvaikalesh/webidl/pull/830.html" title="Last updated on Dec 24, 2019, 1:48 AM UTC (f10d1e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/830/28fadc2...shvaikalesh:f10d1e7.html" title="Last updated on Dec 24, 2019, 1:48 AM UTC (f10d1e7)">Diff</a>

Fix "this" typo in constructor operations example

---

index.bs

This is what browsers actually implement. Tested by https://github.com/web-platform-tests/wpt/pull/21039.
----
Apparently, I didn't quite test what browsers actually do when I added _Throw_ = true in #406. This further illustrates the importance of having tests accompany each spec change.
https://github.com/web-platform-tests/wpt/pull/21039 currently actually tests the spec'd semantics. But I'll fix the PR once this gets LGTM'd.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/832.html" title="Last updated on Jan 14, 2020, 7:49 PM UTC (bd48fcd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/832/ce149d1...TimothyGu:bd48fcd.html" title="Last updated on Jan 14, 2020, 7:49 PM UTC (bd48fcd)">Diff</a>

Call Set with Throw=false for [PutForwards]

---

index.bs

This will make IDL adopt https://infra.spec.whatwg.org/#javascript-string-convert rather than have its own algorithm.
Depends on https://github.com/whatwg/infra/pull/292.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/848.html" title="Last updated on Mar 9, 2020, 12:23 PM UTC (b85f284)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/848/225a115...b85f284.html" title="Last updated on Mar 9, 2020, 12:23 PM UTC (b85f284)">Diff</a>

Align a bit with Infra

---

index.bs

Allows "Let |array| be the result of [=creating a frozen array=] with…".
I guess the wrapping is wrong, but I'm not sure what the rules are in this spec.
***
<a href="https://pr-preview.s3.amazonaws.com/jakearchibald/webidl/pull/851.html" title="Last updated on Mar 11, 2020, 11:10 AM UTC (d0edb65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/851/6844bc4...jakearchibald:d0edb65.html" title="Last updated on Mar 11, 2020, 11:10 AM UTC (d0edb65)">Diff</a>

"creating a frozen array" as link text

---

index.bs

When the name and behaviour of the extended attribute were changed back in
4043b051d492d4a2f21064f0edf91e642c5a6249, various prose around the
specification became somewhat unclear. This tries to make everything agree on
what happens.

Editorial: Better explanation of the TreatNonObjectAsNull extended attribute.

---

index.bs

Part of #796.
This is intended as a better version of https://github.com/heycam/webidl/pull/836 that (on a spec level) uses proxy traps, instead of Web IDL legacy platform objects, to fix the issues noted in https://github.com/heycam/webidl/issues/796#issuecomment-578273849.
This also includes a second commit which uses the suggestions from @bzbarsky in https://github.com/heycam/webidl/pull/836#issuecomment-580977516 to avoid the resulting array having holes. This seems like a good thing in various ways, although I am a little unsure whether I successfully pulled it off.
This pull request also changes how spec authors are expected to interface with the observable array type, per some of the discussions in #836. Here is a pull request to the constructible stylesheets repository to show …

Introduce the observable array type (proxy-based)

---

index.bs

This rewrites some of the text around dictionaries to clear up the confusion in #852, as well as generally try to smooth out the reading experience and definitions. Concrete changes:
* Rewrote "dictionaries are always passed by value" to be more specific and clear.
* Moved "dictionaries must not be used as the type of an attribute or constant" near the top of the dictionary section, commensurate with its importance.
* Removed the terms "present" and "not present"; instead we can use Infra's "exists" for maps.
* Fixed several cases where the overload resolution algorithm discussed arguments being "not present", even though that was only defined for dictionaries. Instead it now correctly talks about "missing".
* Rewrote the discussion of required dictionary members and dictionary members …

Clarifications to dictionary semantics

---

index.bs

As part of #467, this moves the installation of @@iterator/@@asyncIterator/forEach/entries/keys/values to an imperative style, for the cases of pair iterators, value iterators, async iterators, and indexed property getters.
This does not yet make imperative the same methods for maplikes and setlikes, nor does it make the construction of the iterator-related objects and prototype objects themselves imperative.
---
This will help me do #808 more properly. I think it's also a big clarity improvement; in particular how each of the four cases mentioned (pair iterators, value iterators, async iterators, and indexed property getters) is now easy to read off from the algorithm instead of being scattered throughout the section for each method.
***
<a …

Editorial: make more iterator-related stuff imperative

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/869.html" title="Last updated on Apr 8, 2020, 8:29 PM UTC (78861cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/869/42a9d4b...78861cb.html" title="Last updated on Apr 8, 2020, 8:29 PM UTC (78861cb)">Diff</a>

Editorial: add back syntax highlighting for observable array example

---

index.bs

This updates the **WebIDL** interface object creation algorithms to use the [`MakeBasicObject`](https://tc39.es/ecma262/#sec-makebasicobject) abstract operation that was introduced by @domenic in <https://github.com/tc39/ecma262/pull/1460>.
***
<a href="https://pr-preview.s3.amazonaws.com/EB-Forks/webidl/pull/871.html" title="Last updated on Apr 16, 2020, 11:27 AM UTC (85dc069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/871/d5f9651...EB-Forks:85dc069.html" title="Last updated on Apr 16, 2020, 11:27 AM UTC (85dc069)">Diff</a>

refactor: Use `MakeBasicObject`

---

index.bs

This pull request contains a series of commits that together close #350. I suggest we rebase-merge, instead of squash-merge, to better make the individual changes clear from the history.
I've updated #350 with a list of specifications that use these extended attributes, and will work on corresponding pull requests to them.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/870.html" title="Last updated on Apr 8, 2020, 9:37 PM UTC (102a68b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/870/42a9d4b...102a68b.html" title="Last updated on Apr 8, 2020, 9:37 PM UTC (102a68b)">Diff</a>

Rename all legacy extended attributes

---

index.bs

The last commit here (the rest are #802) is a start at addressing #800. It is missing the glue code to pass arguments. I'll discuss over in #800 some of the things I ran in to, but having this here is a nice reference.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/808.html" title="Last updated on Apr 21, 2020, 1:42 PM UTC (13670e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/808/42a9d4b...13670e8.html" title="Last updated on Apr 21, 2020, 1:42 PM UTC (13670e8)">Diff</a>

Add async value iterators and async iterator arguments

---

index.bs

This was missed by @domenic in <https://github.com/heycam/webidl/pull/870>, thus breaking cross‑links from specifications that haven’t been updated.
***
<a href="https://pr-preview.s3.amazonaws.com/EB-Forks/webidl/pull/872.html" title="Last updated on Apr 22, 2020, 4:54 PM UTC (ec7a391)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/872/a03c53a...EB-Forks:ec7a391.html" title="Last updated on Apr 22, 2020, 4:54 PM UTC (ec7a391)">Diff</a>

Editorial: Add missing `oldids` attribute to `[LegacyFactoryFunction]`

---

index.bs

This fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28244, aligning Web IDL objects with the built-in ECMAScript objects (see #226), and updating the spec to match 1/4 browsers (Chrome) instead of 0/4 as it currently does.
(Currently no non-Chrome browsers install Symbol.toStringTag properties on any objects, but instead contradict the ECMAScript specification and use magic to produce [object InterfaceName] / [object InterfaceNamePrototype].)
---
/cc @bzbarsky, who tried to implement this in https://groups.google.com/forum/#!searchin/mozilla.dev.platform/toStringTag%7Csort:relevance/mozilla.dev.platform/IZNh8QAXkFA/me59gpo5PgAJ but got pushback.
/cc @travisleithead and @samweinig about implementing this in Edge and WebKit.
---
As with #356, if there is interest in introducing a …

Only install @@toStringTag on the prototype

---

index.bs

They no longer use InterfaceRest.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/765.html" title="Last updated on Aug 6, 2019, 3:36 PM UTC (cd93b7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/765/13c7e8f...cd93b7f.html" title="Last updated on Aug 6, 2019, 3:36 PM UTC (cd93b7f)">Diff</a>

Fix grammar reference in the definition of callback interfaces.

---

index.bs

Fixes <https://www.w3.org/Bugs/Public/show_bug.cgi?id=25051>.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/776.html" title="Last updated on Aug 23, 2019, 3:38 PM UTC (5ab5e9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/776/34ef605...5ab5e9a.html" title="Last updated on Aug 23, 2019, 3:38 PM UTC (5ab5e9a)">Diff</a>

Forbid overloading operations with Promise and non-Promise return types.

---

index.bs

Blocks <https://github.com/heycam/webidl/pull/857>
This also fixes‑up <https://github.com/heycam/webidl/pull/882>, which missed a `[=default toJSON operation=]` link.
***
<a href="https://pr-preview.s3.amazonaws.com/EB-Forks/webidl/pull/884.html" title="Last updated on May 17, 2020, 4:19 PM UTC (413934c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/884/ea3af2c...EB-Forks:413934c.html" title="Last updated on May 17, 2020, 4:19 PM UTC (413934c)">Diff</a>

Editorial: Fix broken heading tags

---

index.bs

The use of undefined as a sentinel for the end of iteration was problematic for value iterators, where the possible value space could contain undefined.
@TimothyGu, could you take a look?
There's another issue lurking here which is that promises should only be resolved with either Web IDL values (if these are Web IDL `Promise<T>`s) or JS values (if these are JS promises). I considered adding a note explaining that end-of-iteration could be represented as a unique Web IDL/JS object with identity, and a pair could be represented as an appropriate Web IDL dictionary/JS null-prototype object, but I couldn't decide what type of promise these were. I guess we can figure that out as a followup, if we really want to.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/885.html" …

Use an "end of iteration" signal instead of undefined

---

index.bs

This is now supported by **widlparser** and **bikeshed**.

Editorial: Add syntax highlighting to async iterable syntax example

---

index.bs

Previously, we would only set the async iterator's "ongoing promise" to null when the async iterator next steps succeeded. This meant that calling return() after a failed next() would not call the async iterator return steps, thus potentially preventing the cleanup of any associated resources. This changes the spec to reset the ongoing promise after the async iterator next steps complete, regardless of whether they succeed or fail.
Credit to @TimothyGu for finding this in https://github.com/jsdom/webidl2js/pull/224#discussion_r433333677. (Timothy, please review!)
Tests for this are added in the Streams context in various commits of https://github.com/web-platform-tests/wpt/pull/22982.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/891.html" title="Last updated on Jun …

Make async iterator return() and next() more like async generators

---

index.bs

In the ecma262 spec, we've added a [new intrinsic notation form](https://github.com/tc39/ecma262/pull/1376) that will avoid unbounded growth of our list of intrinsics.
Specifically, things like `%ArrayPrototype%` and `%ObjProto_valueOf%` should now be represented as `%Array.prototype%` and `%Object.prototype.valueOf%`, respectively.
Our intention is to delete the "legacy" forms entirely in favor of the dotted forms.
Closes #897.

add links for dotted intrinsic form

---

index.bs

This fixes up <https://github.com/heycam/webidl/pull/871>, where I missed the fact that interface prototype objects of global objects and objects in the prototype chain of global objects have their `[[SetPrototypeOf]]` internal method changed in a way that makes them [immutable prototype exotic objects][immutable-prototype-exotic-objects].
---
Changing the `[[SetPrototypeOf]]` method of the result of [`OrdinaryObjectCreate`] goes against the intention of separating [`OrdinaryObjectCreate`] and [`MakeBasicObject`], so this fixes that.
[immutable-prototype-exotic-objects]: https://tc39.es/ecma262/#sec-immutable-prototype-exotic-objects
[`OrdinaryObjectCreate`]: https://tc39.es/ecma262/#sec-ordinaryobjectcreate
[`MakeBasicObject`]: https://tc39.es/ecma262/#sec-makebasicobject
***
<a …

Editorial: Avoid changing internal methods of ordinary objects

---

index.bs

Follow-up of #357.
This change aligns WebIDL [namespace objects](https://heycam.github.io/webidl/#namespace-object) with ECMA-262 ones like [`Math`](https://tc39.es/ecma262/#sec-math-@@tostringtag) and [`Atomics`](https://tc39.es/ecma262/#sec-atomics-@@tostringtag).
Chrome (84.0.4126.0) already implements this PR:
```js
WebAssembly[Symbol.toStringTag] // => "WebAssembly"
```
_cc_ @domenic
***
<a href="https://pr-preview.s3.amazonaws.com/shvaikalesh/webidl/pull/873.html" title="Last updated on Jul 21, 2020, 1:48 PM UTC (083d283)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/873/350fb2a...shvaikalesh:083d283.html" title="Last updated on Jul 21, 2020, 1:48 PM UTC (083d283)">Diff</a>

Install @@toStringTag on namespace objects

---

index.bs

void -> undefined, and allow it anywhere.

---

index.bs

This is needed for the CSSOM spec, as that allows to use USVString as
the underlying string type.
Given the USVString conversion to JS values is already calling into the
DOMString conversion, there's no need to modify that section even, which
is great.
cc https://github.com/w3c/csswg-drafts/issues/5010

Allow to use LegacyNullToEmptyString on USVString.

---

index.bs

Require [Exposed] even when marked as [LegacyNoInterfaceObject]

---

index.bs

"React to a promise"'s default handlers used to return undefined rather than propagating the resolved value or the rejection reason to the returned promise. This change fixes that, and changes "upon fulfillment" and "upon rejection" to return the resulting promise.
Closes #921.

Fix "react to a promise"'s default handlers

---

index.bs

WebIDL currently defines a `[SecureContext]` extended attribute that
governs whether or not a given construct is exposed within a given
context. This patch defines a similar `[CrossOriginIsolated]` attribute
to govern exposure based on cross-origin isolation.
This supports the broader Securer Contexts proposal
(https://github.com/mikewest/securer-contexts), which aims to guide
spec authors to combat threats we've started paying more attention to
over the last few years.
Closes https://github.com/heycam/webidl/issues/875.
***
<a href="https://pr-preview.s3.amazonaws.com/mikewest/webidl/pull/883.html" title="Last updated on Jun 25, 2020, 10:39 AM UTC (4a46b22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/883/9a739b5...mikewest:4a46b22.html" title="Last updated …

Define the `[CrossOriginIsolated]` extended attribute.

---

index.bs

I'm gonna be pushing some Bikeshed fixes that link more WebIDL types that are currently left unlinked in IDL blocks, and ObservableArray having a gratuitously different `lt` value than similar types like FrozenArray is troublesome.

Fix ObservableArray's lt

---

index.bs

The note was added in #180, a few months before https://github.com/tc39/ecma262/pull/833 was merged.
_cc_ @domenic @bzbarsky
***
<a href="https://pr-preview.s3.amazonaws.com/shvaikalesh/webidl/pull/925.html" title="Last updated on Oct 15, 2020, 9:21 AM UTC (ec9e010)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/925/accdef1...shvaikalesh:ec9e010.html" title="Last updated on Oct 15, 2020, 9:21 AM UTC (ec9e010)">Diff</a>

Update obsolete note on duplicate Proxy [[OwnPropertyKeys]] entries

---

index.bs

This patch adds a bigint type to WebIDL with the following properties:
- bigint corresponds directly to BigInt
- The conversion from JS is based on ToBigInt, namely it throws on Number.
- bigint is not grouped as a "numeric" type, as this category is often
used to refer to types which have a JavaScript representation of Number.
- bigint is included in the overloading resolution algorithm, and it's
possible to overload a function for BigInt and numeric arguments.
Although it may be on the early side for such a change, the lack of
BigInt WebIDL integration is already coming up in some designs for integrating
BigInt with the Web Platform, such as https://github.com/w3c/IndexedDB/pull/231
***
<a href="https://pr-preview.s3.amazonaws.com/littledan/webidl/pull/525.html" title="Last updated on …

Add bigint type

---

Makefile

This PR updates the installation guide url in `Makefile`. (The current one doesn't look working now.)

Meta: update bikeshed install guide url

---

index.bs

No major browser implements these 3 error-name-to-error-code mappings in DOMException constructor. So this PR suggests removing these 3 entries from the table.
We found this while updating web platform test at https://github.com/web-platform-tests/wpt/pull/27181.
cc @domenic

Remove disused entries from error names table (2.8.1.)

---

index.bs

In order for the following line, pop(), to return "employeeB", employeeB needs to be on the "top" of the stack, meaning the splice should remove employeeC at index 2. :)

Adjust sample code so it makes more sense

---

README.md

Ecmarkup link is currently 404. Update to the new page for it, at https://tc39.es/ecmarkup/ .

update Ecmarkup link

---

index.bs

* Added `undefined` to the distinguishability table
* Removed text from any/union conversion that handled `undefined` specially, now that it's just an ordinary IDL value.
* Editorially, cleaned up the markup for the distinguishability table, and changed one unrelated code example to use double-quotes on a few strings, as it was inconsistent with quote usage elsewhere in the same example, and the empty string messed up Bikeshed's syntax-highlighting for the rest of the spec from that point on.
Currently a draft because there's an open question in <https://github.com/heycam/webidl/issues/962#issuecomment-796938662>, don't merge until that's answered and likely has another commit addressing it.

More fixes for `undefined`

---

index.bs

This example was adapted from a previous one in
https://github.com/heycam/webidl/pull/433, but things are much simpler
now and the example makes it seem more complicated than it really is.
Make the points inheritance and mixins separately.
This also fixes the order of attributes on the returned JSON object,
which was wrong the original example. The attributes of the base
interface should be included first. Reverse the inheritance order in
the example to make this clearer, matching `interface B : A` in two
other examples.
Fixes https://github.com/heycam/webidl/issues/979.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webidl/pull/980.html" title="Last updated on Apr 24, 2021, 7:04 AM UTC (184b465)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/980/ecfa7fb …

Editorial: simplify the example on default toJSON()

---

index.bs

Although it was un-exported from HTML recently, Web IDL is one of the very few specs which has legitimate reason to link to it.

Meta: fix linking to "incumbent settings object"

---

index.bs

* Introduces algorithms for creating ArrayBuffers and ArrayBufferViews from byte sequences
* Introduces algorithms for writing into ArrayBuffers and ArrayBufferViews, replacing "get a reference to the bytes held by the buffer source".
* Introduces "transfer" for an ArrayBuffer.
* Introduces "byte length", "underlying buffer", and "detached" for introspecting a BufferSource.
* Improves the specification for "get a copy of the bytes held by a buffer source" and "detach".
Updates to dependent specs:
* https://github.com/WebAudio/web-audio-api/pull/2358
* https://github.com/whatwg/streams/pull/1130
* https://github.com/whatwg/encoding/pull/262
I'd like review here from @syg and/or other ES editors, especially for the "write" operation.

Add and improve operations on BufferSources

---

index.bs

Now that we have [the `bigint` type][idl-bigint] (<https://github.com/heycam/webidl/pull/525>), it makes sense to add these as well.
[idl-bigint]: https://heycam.github.io/webidl/#idl-bigint
---
review?(@domenic, @littledan, @heycam, @TimothyGu)

Normative: Add `BigInt64Array` and `BigUint64Array`

---

index.bs

Per https://heycam.github.io/webidl/#es-observable-array, 
> Instead of the usual conversion algorithms, observable array types have special handling as part of the [attribute getter]((https://heycam.github.io/webidl/#dfn-attribute-getter) and [attribute setter](https://heycam.github.io/webidl/#dfn-attribute-setter) algorithms.
So I think using observable array type as the inner type of an observable array type, e.g. `ObservableArray<ObservableArray<boolean>>`, or a nullable type, e.g. `ObservableArray<boolean>?`, should be disallowed. Otherwise, spec isn't clear how to handle/get the observable array exotic objects for the inner types.

More fixes for observable array type

---

index.bs

This commit adds the [AllowResizable] extended attribute, which allow
BufferSources to take resizable buffers. It composes with [AllowShared]
in the obvious way. The default behavior is unchanged, with only
fixed-length buffers allowed.
Proposal link: https://github.com/tc39/proposal-resizablearraybuffer

Integrate with the resizable buffers proposal

---

index.bs

This patch adds support in WebIDL for declaring an interface available
in all contexts.
Closes #468 
This PR follows the syntax and outline suggested by @tobie . Thanks for your clear instructions here.
***
<a href="https://pr-preview.s3.amazonaws.com/littledan/webidl/pull/526.html" title="Last updated on Feb 23, 2018, 2:43 PM GMT (2e23cfb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/526/3750d7a...littledan:2e23cfb.html" title="Last updated on Feb 23, 2018, 2:43 PM GMT (2e23cfb)">Diff</a>

Add [Exposed=*] to expose on all globals

---

index.bs

Fixes #1057
***
<a href="https://whatpr.org/webidl/1058.html" title="Last updated on Nov 2, 2021, 10:15 PM UTC (1a414f2)">Preview</a> | <a href="https://whatpr.org/webidl/1058/59dae6f...1a414f2.html" title="Last updated on Nov 2, 2021, 10:15 PM UTC (1a414f2)">Diff</a>

Use [=tuple=] instead of [=pair=]

---

index.bs

(If this reminds you of the FS PR, it's because I used copy-and-paste.)
***
<a href="https://whatpr.org/webidl/1076.html" title="Last updated on Dec 13, 2021, 1:29 PM UTC (cad705c)">Preview</a> | <a href="https://whatpr.org/webidl/1076/0105032...cad705c.html" title="Last updated on Dec 13, 2021, 1:29 PM UTC (cad705c)">Diff</a>

Editorial: use cite element in IPR section

---

index.bs

Closes #1010. Closes #1043 by superseding it (since we cannot currently accept pseudonymous contributions 😢).
***
<a href="https://whatpr.org/webidl/1082.html" title="Last updated on Jan 18, 2022, 10:39 PM UTC (61d95fe)">Preview</a> | <a href="https://whatpr.org/webidl/1082/d8b9790...61d95fe.html" title="Last updated on Jan 18, 2022, 10:39 PM UTC (61d95fe)">Diff</a>

Fix distinguishability for bigint and numeric types

---

index.bs

This helps specifications avoid reaching into internal slots. Closes #829.
Also includes some editorial touchups to nearby promise definitions.
***
<a href="https://whatpr.org/webidl/1090.html" title="Last updated on Feb 2, 2022, 10:17 PM UTC (c930213)">Preview</a> | <a href="https://whatpr.org/webidl/1090/ae0de45...c930213.html" title="Last updated on Feb 2, 2022, 10:17 PM UTC (c930213)">Diff</a>

Introduce "mark as handled" for promises

---

index.bs

As part of the https://github.com/tc39/ecma262/pull/2547 ecma262 has reformed how it deals with Completion Records. See https://github.com/tc39/ecma262/issues/253#issuecomment-1050160672 for a brief description of when to use `?` vs `!` vs nothing at all.
This PR was generated in part by [this script](https://gist.github.com/syg/47652ec9ee938707b93807a5b3fed768) being passed `index.bs` and a locally generated copy of ecma262's `biblio.json`.
It is probably easier to review this PR commit-by-commit.
This is the counterpart to https://github.com/whatwg/html/pull/7661.
/cc other ecma262 editors @bakkot and @michaelficarra
***
<a href="https://whatpr.org/webidl/1111.html" title="Last updated on Mar 1, 2022, 11:56 PM UTC (ae45b77)">Preview</a> | <a …

Editorial: Completion reform for ECMAScript AOs

---

index.bs

Exporting the "backing list" definition for observable arrays, since most (all?) definitions of the observable array algos will need to reference it.
***
<a href="https://whatpr.org/webidl/1124.html" title="Last updated on Apr 19, 2022, 8:32 PM UTC (5bf62d2)">Preview</a> | <a href="https://whatpr.org/webidl/1124/2c45ffc...5bf62d2.html" title="Last updated on Apr 19, 2022, 8:32 PM UTC (5bf62d2)">Diff</a>

Export observable array attribute/backing list

---

index.bs

I was surprised and glad to see that getters/setters have defined terminology to work from now, but unfortunately the dfns weren't exported.
I also initially wrote my algos explicitly taking in a |this| (and a |val| for the setters) and only coincidentally remembered that [=this=] exists, which is also when I learned that [=the given value=] exists. To help myself and others in the future, I've dropped a Note here to remind of their existence, since the terms are defined elsewhere in the spec and not linked anywhere nearby.
***
<a href="https://whatpr.org/webidl/1130.html" title="Last updated on Apr 26, 2022, 5:50 PM UTC (4643902)">Preview</a> | <a href="https://whatpr.org/webidl/1130/c2b9c12...4643902.html" title="Last updated on Apr 26, 2022, 5:50 PM UTC (4643902)">Diff</a>

Export getter/setter steps, and note the tools you have access to when defining them.

---

index.bs

Per #835, the "type name" concept is no longer actively used by the specification. It was originally introduced in <https://github.com/whatwg/webidl/commit/8e66595d495b40d05c9926fbd01b0fa0be5ecb6a>, where it was necessary to create a author-observable name for the Array subclasses created by the `T[]` syntax, but that syntax is dead. We've been keeping carrying the concept forward out of inertia since then.
The only remaining usage of it (besides all the places where types define their type name) was in the algo for converting ES values to the IDL buffer source types; it's used solely to verify that the ES value is of the same-named type as the IDL type it's being converted to. Since the "type name" of the buffer source types was just defined as "the name of the type itself", I inlined …

Remove the concept of 'type name'. Closes #835

---

index.bs

Fixes #254, fixes #824.
This PR switches maplike and setlike interfaces from using a [[BackingMap]]/[[BackingSet]] ES Map/Set to use an Infra map/set instead. As explained in #254 and #824, this makes the interfaces vastly easier to work with in spec-ese (you can directly manipulate an Infra map/set, rather than having to carefully perform the ES algo dance) , and removes some underdefined behavior (as currently defined, the algorithms look up and utilize the equivalent methods on Map.prototype and Set.prototype, which can be author-supplied).
Unless the author is relying on the "replace the Map.prototype methods" behavior (I haven't tested if impls actually allow this, in any case), this change should be undetectable, and just result in specs using maplike or setlike interfaces having an …

WIP: switching maplike/setlike to use infra maps and sets

---

index.bs

Closes #1139.
***
<a href="https://whatpr.org/webidl/1140.html" title="Last updated on May 5, 2022, 10:45 AM UTC (ef8513f)">Preview</a> | <a href="https://whatpr.org/webidl/1140/271cff8...ef8513f.html" title="Last updated on May 5, 2022, 10:45 AM UTC (ef8513f)">Diff</a>

Exclude undefined from the PrimitiveType in grammar

---

index.bs

Closes #1097
* Deno
* Cloudflare Workers
* Chromium
* Mozilla
N/A
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1305399
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1765992
* Safari: https://bugs.webkit.org/show_bug.cgi?id=239672
* Deno: already supported
* Node.js: https://github.com/nodejs/node/issues/42831
***
<a href="https://whatpr.org/webidl/1098.html" title="Last updated on May 10, 2022, 10:13 AM UTC (2915f6b)">Preview</a> | <a href="https://whatpr.org/webidl/1098/ae0de45...2915f6b.html" title="Last updated on May 10, 2022, 10:13 AM UTC (2915f6b)">Diff</a>

Allow same identifier in static and regular ops

---

index.bs

This was a typo introduced in https://github.com/whatwg/webidl/pull/1111; cc @syg. Sorry I didn't catch it at the time. Context follows but feel free to skip it.
---
[`?`](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-returnifabrupt-shorthands) is a macro in the JS spec which expands to [`ReturnIfAbrupt`](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-returnifabrupt) and which is used when possible errors need to get propagated immediately. In the case of non-errors it unwraps the completion record for use in later steps.
[`IfAbruptRejectPromise`](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-ifabruptrejectpromise) is a macro in the JS spec which is used when possible errors need to get wrapped up into rejected promises. As …

Editorial: fix uses of `?` with `IfAbruptRejectPromise`

---

index.bs

fixes #972
***
<a href="https://whatpr.org/webidl/1173.html" title="Last updated on Jul 23, 2022, 12:23 PM UTC (ea276b1)">Preview</a> | <a href="https://whatpr.org/webidl/1173/7c6e257...ea276b1.html" title="Last updated on Jul 23, 2022, 12:23 PM UTC (ea276b1)">Diff</a>

Fix incorrect wording in `2.9. Enumerations`

---

index.bs

This is fixing an issue Dan caught, where it turns out that, since the global object inside the ShadowRealm is not defined using IDL, it's not an "interface" and hence not included in any "own exposure set". To that end, it removes the "the set of all global names of all interfaces which have the [Global] extended attribute" wording, which was pretty clunky anyway.
CC @leobalter @littledan 
* I'm assuming this is fine, since `Exposed=*` needs this to work as intended.
* Existing tests cover this.
* Chrome: …
* Firefox: …
* Safari: …
* Deno: …
* Node.js: …
(I still need to review which implementations, if any, need to change for this.)
***
[PR …

Ensure [Expose=*] works when the global object is not defined using IDL

---

index.bs

This prevents a possible confusion from the word "instance", as it theoretically can sound like each instance should own the property.
Also, the paragraph mentions "native Error objects" so it's natural to match that and say "DOMException objects".
See also https://github.com/whatwg/webidl/issues/1186#issuecomment-1241401986.
***
<a href="https://whatpr.org/webidl/1187.html" title="Last updated on Sep 9, 2022, 9:44 PM UTC (40b9848)">Preview</a> | <a href="https://whatpr.org/webidl/1187/d720ef3...40b9848.html" title="Last updated on Sep 9, 2022, 9:44 PM UTC (40b9848)">Diff</a>

Remove the word "instances" from DOMException custom bindings

---

index.bs

* Deprecate "URLMismatchError". Since https://github.com/whatwg/html/commit/b261d162b451a646d5597689f0b831a722a19182 it is no longer used by anything in the spec ecosystem.
* Make it clearer that "InUseAttributeError" and "InvalidNodeTypeError" are DOM-specific, by tweaking their descriptions and adding the [DOM] reference.
* Make it clearer that "ConstraintError", "TransactionInactiveError", "ReadOnlyError", and "VersionError" are IndexedDB-specific, by adding the [INDEXEDDB] reference.
***
<a href="https://whatpr.org/webidl/1202.html" title="Last updated on Sep 27, 2022, 10:38 AM UTC (37cfd25)">Preview</a> | <a href="https://whatpr.org/webidl/1202/b03aa9e...37cfd25.html" title="Last updated on Sep 27, 2022, 10:38 AM UTC (37cfd25)">Diff</a>

Improvements to DOMException error names table

---

Makefile
index.bs
package.json
review-drafts/2022-03.bs

Closes #1195 by using a new attribute, grammar-fill-with="", which won't get removed by Bikeshed's "slim build artifact" setting.
This will not work until https://github.com/tobie/webidl-grammar-post-processor/pull/2 is merged and released as v1.0.0.
***
<a href="https://whatpr.org/webidl/1200.html" title="Last updated on Sep 28, 2022, 6:56 AM UTC (1ead4cb)">Preview</a> | <a href="https://whatpr.org/webidl/1200/fb27b8a...1ead4cb.html" title="Last updated on Sep 28, 2022, 6:56 AM UTC (1ead4cb)">Diff</a>

Meta: fix the grammar post processor on Review Drafts

---

index.bs

Do not have members that are both optional and nullable.
Fixes #1204.
***
<a href="https://whatpr.org/webidl/1205.html" title="Last updated on Sep 29, 2022, 6:59 AM UTC (5dcc4d0)">Preview</a> | <a href="https://whatpr.org/webidl/1205/9e4ce33...5dcc4d0.html" title="Last updated on Sep 29, 2022, 6:59 AM UTC (5dcc4d0)">Diff</a>

Make PaintOptions example a better role model.

---

index.bs

This makes the properties generated by the maplike/setlike declarations consistent with properties generated by other IDL constructs such as operation and attribute declarations. (That includes, e.g., explicitly-specified has/get/set/delete operations!) This is also consistent with the generated properties for iterable declarations.
The @@iterator symbol property remains non-enumerable, like it is for iterable declarations, and like all other symbol-named properties are.
Closes #738.
* Matches current Blink implementation
* Gecko support in https://github.com/whatwg/webidl/issues/738#issuecomment-1250169937
* https://github.com/web-platform-tests/wpt/pull/36123
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1344001
* Firefox: …

Make setlike/maplike generated properties enumerable

---

index.bs

***
<a href="https://whatpr.org/webidl/1215.html" title="Last updated on Oct 13, 2022, 5:14 AM UTC (9996240)">Preview</a> | <a href="https://whatpr.org/webidl/1215/e3d0c74...9996240.html" title="Last updated on Oct 13, 2022, 5:14 AM UTC (9996240)">Diff</a>

Document what defaults are ok for dictionary values.

---

index.bs

Fixes #976
Some other candidates are there, but I think the term `monospaced` is the most intuitive when looking at the grammar:
>*CallbackOrInterfaceOrMixin* `::`
>    `callback` *CallbackRestOrInterface*
>    `interface` *InterfaceOrMixin*
It's clear which are the monospaced terminal symbols.
***
<a href="https://whatpr.org/webidl/1216.html" title="Last updated on Oct 13, 2022, 6:22 AM UTC (2bf7d7c)">Preview</a> | <a href="https://whatpr.org/webidl/1216/bc7cb7a...2bf7d7c.html" title="Last updated on Oct 13, 2022, 6:22 AM UTC (2bf7d7c)">Diff</a>

"Quoted terminal symbols" are now monospaced

---

index.bs

Refresh
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/webidl/1209.html" title="Last updated on Oct 13, 2022, 7:56 AM UTC (b2700b8)">Preview</a> | <a href="https://whatpr.org/webidl/1209/bf88a5a...b2700b8.html" title="Last updated on Oct 13, 2022, 7:56 AM UTC (b2700b8)">Diff</a>

Fix typo - s/an/a before "NotAllowed"

---

index.bs

* Everyone already implements this correctly
* https://github.com/web-platform-tests/wpt/pull/36950
* Chromium: N/A
* Gecko: N/A
* WebKit: N/A
* Deno: Will comment on https://github.com/denoland/deno/issues/16068
* Node.js: N/A
* webidl2.js: N/A
* widlparser: N/A
***
<a href="https://whatpr.org/webidl/1232.html" title="Last updated on Nov 15, 2022, 5:23 AM UTC (379aa27)">Preview</a> | <a href="https://whatpr.org/webidl/1232/7e9e8e4...379aa27.html" title="Last updated on Nov 15, 2022, 5:23 AM UTC (379aa27)">Diff</a>

Fix getter name for maplike/setlike size

---

index.bs

This is purely an editorial change. It fixes the link errors the current spec has (around Memory and Memory/buffer), and additionally removes a large number of the explicit anchors defined in the spec. For the most part these removals were simple; in a few places I fixed the linking syntax down in the spec body as well.
The abstract-op anchors left behind just aren't being detected by WebRef; [I opened an issue about them](https://github.com/w3c/webref/issues/888). When that's fixed we should be able to remove that entire block.
A number of the remaining anchors are things that should probably be fixed in ECMAScript, but I don't have bandwidth to do that right now. I haven't done a full accounting of the remaining anchor values; some of them might also be removable right now.
***
<a …

Fix links, remove as many anchor definitions as possible

---

index.bs

In #1138 I accidentally made setlike's add() return the added value, like delete(). It originally returned the setlike itself. This PR returns the spec to the original behavior.
skipping the checklist since this is just returning the spec's behavior to how it was before the #1138 PR, which was not *intended* to change this aspect.
***
<a href="https://whatpr.org/webidl/1269.html" title="Last updated on Feb 28, 2023, 8:51 PM UTC (19c68d0)">Preview</a> | <a href="https://whatpr.org/webidl/1269/50afeeb...19c68d0.html" title="Last updated on Feb 28, 2023, 8:51 PM UTC (19c68d0)">Diff</a>

setlike.add() is meant to return the setlike. Fixes #1268

---

index.bs

close #1280.
***
<a href="https://whatpr.org/webidl/1281.html" title="Last updated on Mar 16, 2023, 9:28 PM UTC (5c207b4)">Preview</a> | <a href="https://whatpr.org/webidl/1281/8813044...5c207b4.html" title="Last updated on Mar 16, 2023, 9:28 PM UTC (5c207b4)">Diff</a>

Allow static operations with the same names as default operations in Maplike/Setlike/Iterable/AsyncIterable

---

review-drafts/2023-03.bs

The [March 2023 Review Draft](https://webidl.spec.whatwg.org/review-drafts/2023-03/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/webidl/1284.html" title="Last updated on Mar 20, 2023, 8:08 AM UTC (881e22f)">Preview</a> | <a href="https://whatpr.org/webidl/1284/10a2e88...881e22f.html" title="Last updated on Mar 20, 2023, 8:08 AM UTC (881e22f)">Diff</a>

Review Draft Publication: March 2023

---

index.bs

This patch clarifies [#named-properties-object](https://webidl.spec.whatwg.org/#named-properties-object) per whatwg/html#9068 by adding a note that reads
> The [[OwnPropertyKeys]] internal method of a named properties object continues to use [OrdinaryOwnPropertyKeys](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinaryownpropertykeys), unlike the counterpart for [legacy platform objects](https://webidl.spec.whatwg.org/#dfn-legacy-platform-object). Since named properties are not “real” own properties, they will not be returned by this internal method.
The use of “real” in scare quotes is based on the wording in [#es-legacy-platform-objects](https://webidl.spec.whatwg.org/#es-legacy-platform-objects), but I’m open to suggestions for a more precise …

Clarify #named-properties-object

---

index.bs

This might be sufficient for #335, but I think it's useful for spec authors to go roughly this far even if there's more to do to completely fix that issue. 
cc/ @domfarolino 
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/webidl/1287.html" title="Last updated on Apr 21, 2023, 3:33 PM UTC (5690199)">Preview</a> | <a href="https://whatpr.org/webidl/1287/a35410d...5690199.html" title="Last updated on Apr 21, 2023, 3:33 PM UTC (5690199)">Diff</a>

Editorial: Define the WebIDL string types in terms of Infra types.

---

index.bs

Infra already explains the relevant details and ByteString is not at all suitable for UTF-8 data.
Also hyphenate "x bit" throughout.
cc @jyasskin
***
<a href="https://whatpr.org/webidl/1298.html" title="Last updated on Apr 26, 2023, 2:50 PM UTC (48314da)">Preview</a> | <a href="https://whatpr.org/webidl/1298/4c018c6...48314da.html" title="Last updated on Apr 26, 2023, 2:50 PM UTC (48314da)">Diff</a>

Editorial: remove remaining UTF-8 and UTF-16 references

---

index.bs

***
<a href="https://whatpr.org/webidl/1299.html" title="Last updated on Apr 28, 2023, 8:27 AM UTC (db6050a)">Preview</a> | <a href="https://whatpr.org/webidl/1299/29ea31b...db6050a.html" title="Last updated on Apr 28, 2023, 8:27 AM UTC (db6050a)">Diff</a>

Editorial: Fix typo in the overload resolution algorithm

---

index.bs

See discussion in https://github.com/whatwg/webidl/issues/1168#issuecomment-1183851493.
This also includes some updates to all exception creation and throwing, such as reflecting how messages are actually passed along in practice, or using Web IDL infrastructure to create DOMException instances instead of Construct()ing them.
It seems some places were already doing this sort of thing, such as https://w3c.github.io/webtransport/#web-transport-error-interface and I think some media thing. For WebTransport, it seems like they aren't violating the letter of the current spec since they were never throwing such `WebTransportError`s or treating them like exceptions, instead just passing them through streams machinery and so on. But I think it's a good idea to codify this.
Note that …

Allow DOMException subclasses to be used as exceptions

---

index.bs

Generally IDL objects have been 1:1 with ECMAScript objects, except for SharedArrayBuffer. That was instead represented as [AllowShared] ArrayBuffer, although that includes ArrayBuffer as well. This created a number of challenges, e.g., how to return a SharedArrayBuffer object.
So we make these changes here that will also require corresponding downstream fixes:
* SharedArrayBuffer is now its own type.
* [AllowShared] only applies to buffer view types.
* AllowSharedBufferSource takes over from [AllowShared] BufferSource.
Fixes #865 and fixes #961.
* Chromium per https://github.com/whatwg/webidl/issues/961#issuecomment-892616473
* WebKit
* N/A
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1455098
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1838639
* WebKit: …

Give SharedArrayBuffer a dedicated type

---

index.bs

They used to return JS Completions, contrary to the claim at their definitions.
***
<a href="https://whatpr.org/webidl/1324.html" title="Last updated on Jun 20, 2023, 9:08 PM UTC (5d50915)">Preview</a> | <a href="https://whatpr.org/webidl/1324/c45a0f3...5d50915.html" title="Last updated on Jun 20, 2023, 9:08 PM UTC (5d50915)">Diff</a>

Make call and invoke either return an IDL value or throw.

---

index.bs

Without this, the exception skips the "clean up" steps, which seems bad. I expect everyone's already implemented this correctly.
***
<a href="https://whatpr.org/webidl/1323.html" title="Last updated on Jun 21, 2023, 7:18 PM UTC (13f6a82)">Preview</a> | <a href="https://whatpr.org/webidl/1323/95f57dd...13f6a82.html" title="Last updated on Jun 21, 2023, 7:18 PM UTC (13f6a82)">Diff</a>

Editorial: Handle exceptions thrown while converting 'invoke's return value.

---

index.bs

This definition is referenced by the Web Serial API and the link was recently broken by refactoring in this repository.
***
<a href="https://whatpr.org/webidl/1328.html" title="Last updated on Jun 23, 2023, 10:02 PM UTC (39284cd)">Preview</a> | <a href="https://whatpr.org/webidl/1328/c3b4e97...39284cd.html" title="Last updated on Jun 23, 2023, 10:02 PM UTC (39284cd)">Diff</a>

Export create algorithm for ArrayBufferView

---

package.json

Inspired by #1329, but does not actually fix the warnings.
I manually verified that nothing changes in the output.

Meta: update build dependencies

---

index.bs

PR #1270's substitutions ended up turning some occurrences of
{{ECMAScript/TypeError}}
into
<l spec=ecmascript>{{TypeError}}</l>}
which a trailing "}" character at the end.
***
<a href="https://whatpr.org/webidl/1351.html" title="Last updated on Aug 14, 2023, 2:03 PM UTC (1139bc2)">Preview</a> | <a href="https://whatpr.org/webidl/1351/c2ca1a4...1139bc2.html" title="Last updated on Aug 14, 2023, 2:03 PM UTC (1139bc2)">Diff</a>

Remove extra }'s from some TypeError references

---

index.bs

Per https://github.com/whatwg/webidl/issues/544#issuecomment-1649826889: I can't come up with a good reasoning to add an exception for `[Global]` interfaces, even tho the code like `with (window) { ... }` probably doesn't exist in the wild.
_cc_ @bathos
***
<a href="https://whatpr.org/webidl/1361.html" title="Last updated on Sep 10, 2023, 9:06 PM UTC (f819707)">Preview</a> | <a href="https://whatpr.org/webidl/1361/bc4a416...f819707.html" title="Last updated on Sep 10, 2023, 9:06 PM UTC (f819707)">Diff</a>

Editorial: Remove the note on `@@unscopables` and `[Global]` interfaces

---

index.bs

A step like `! CreateDataProperty(...)` asserts only that `[[DefineOwnProperty]]` is an ordinary method that can't throw, but doesn't assert that property creation is a guaranteed success because `[[DefineOwnProperty]]` only returns boolean status (it is [`Object.defineProperty`](https://tc39.es/ecma262/#sec-object.defineproperty) that throws a `TypeError`).
This change replaces these steps with `! CreateDataPropertyOrThrow(...)`, asserting that property is defined successfully since all its call sites operate on newly-created objects with no non-configurable properties.
ECMA-262 has no occurrences of `! CreateDataProperty(...)`.
Also, this change replaces "Call" with "Perform", which is a new convention of ECMA-262.
***
<a href="https://whatpr.org/webidl/1359.html" title="Last updated on …

Editorial: Use CreateDataPropertyOrThrow abstract op in more places

---

index.bs

This change aligns the spec with WebKit and Gecko, favouring throwing an error rather than failing silently, which is more idiomatic (all ECMA-262 built-ins are strict mode code).
WebIDL spec attempts to throw a TypeError whenever permitted by web reality, like for [invalid `this` value](https://webidl.spec.whatwg.org/#ref-for-LegacyLenientThis%E2%91%A8). This change is a step towards that direction.
See also: https://github.com/whatwg/html/pull/9722.
* Implemented in WebKit since https://github.com/WebKit/WebKit/commit/1e336abec35481176bd436ef85e1e19bfd24057b.
* Gecko
* https://github.com/web-platform-tests/wpt/pull/41902
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1480949
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more …

Throw TypeError if `[Replaceable]` setter fails to reconfigure the property

---

index.bs

At some point the transform that rotated the #distinguishable-table column headers stopped matching up; I'm not sure why. The `translate()` just needed a little shifting to get them back into alignment.
***
<a href="https://whatpr.org/webidl/1380.html" title="Last updated on Dec 19, 2023, 11:54 PM UTC (5630491)">Preview</a> | <a href="https://whatpr.org/webidl/1380/10e559d...5630491.html" title="Last updated on Dec 19, 2023, 11:54 PM UTC (5630491)">Diff</a>

Fix rotated column headers on Distinguishable table

---

index.bs

This is required to define the ShadowRealm global object in IDL.
* …
* …
* https://github.com/web-platform-tests/wpt/pull/43756
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/webidl/1381.html" title="Last updated on Jan 11, 2024, 4:32 PM UTC (56966c3)">Preview</a> | <a href="https://whatpr.org/webidl/1381/8e9affa...56966c3.html" title="Last updated on Jan 11, 2024, 4:32 PM UTC (56966c3)">Diff</a>

Allow for global objects with a mutable prototype chain

---

index.bs

Fixes #1191
* Chromium
* …
* ...
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/webidl/1353.html" title="Last updated on Oct 5, 2023, 7:21 PM UTC (c3bf764)">Preview</a> | <a href="https://whatpr.org/webidl/1353/84c4ccc...c3bf764.html" title="Last updated on Oct 5, 2023, 7:21 PM UTC (c3bf764)">Diff</a>

Add distinguishable state for cb and dictionary-like

---

index.bs

Fixes #1389
There's still 4 "review drafts" from 2023 that refer to CreateMethodProperty, but I assume those shouldn't be updated?
***
<a href="https://whatpr.org/webidl/1391.html" title="Last updated on Mar 11, 2024, 6:08 PM UTC (53f0feb)">Preview</a> | <a href="https://whatpr.org/webidl/1391/400ce04...53f0feb.html" title="Last updated on Mar 11, 2024, 6:08 PM UTC (53f0feb)">Diff</a>

Replace CreateMethodProperty with DefineMethodProperty

---

review-drafts/2024-03.bs

The [March 2024 Review Draft](https://webidl.spec.whatwg.org/review-drafts/2024-03/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/webidl/1395.html" title="Last updated on Mar 18, 2024, 1:38 PM UTC (8dc9976)">Preview</a> | <a href="https://whatpr.org/webidl/1395/5a2802b...8dc9976.html" title="Last updated on Mar 18, 2024, 1:38 PM UTC (8dc9976)">Diff</a>

Review Draft Publication: March 2024

---

index.bs

The [Float16Array](https://github.com/tc39/proposal-float16array) proposal for JavaScript adds a new TypedArray type holding IEEE binary16 floats. This PR adds it to all of the lists of TypedArray types in WebIDL.
Implementations of the proposal are underway in at least [Chrome](https://bugs.chromium.org/p/v8/issues/detail?id=14012) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1833646), though it'll be some time before they're shippable. I don't know what the appropriate time to merge this is but I figured I should at least open it.
This is a JS feature, but adding it to ArrayBufferView has implications for any API which takes a generic TypedArray, which is quite a few of them. Does that imply they all need new tests? Hopefully not?
Fixes …

Add Float16Array

---

index.bs

`GetIterator` no longer exists in this form (it tries to obtain the method when passed `sync` or `async`), and `IteratorStep`/`IteratorValue` have been merged into a single AO for convenience.
***
<a href="https://whatpr.org/webidl/1409.html" title="Last updated on Jun 8, 2024, 2:00 AM UTC (80aef16)">Preview</a> | <a href="https://whatpr.org/webidl/1409/ca9d63d...80aef16.html" title="Last updated on Jun 8, 2024, 2:00 AM UTC (80aef16)">Diff</a>

Update 'Creating a sequence from an iterable' to use new iterator AOs

---

index.bs

Also an an example of how to specify frozen array attributes.
Closes #1399.
* Should be compatible with all code
* Not needed
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: N/A
* Node.js: N/A
***
<a href="https://whatpr.org/webidl/1413.html" title="Last updated on Jun 26, 2024, 2:22 AM UTC (9492715)">Preview</a> | <a href="https://whatpr.org/webidl/1413/f2b124e...9492715.html" title="Last updated on Jun 26, 2024, 2:22 AM UTC (9492715)">Diff</a>

Disallow non-attribute frozen arrays

---

index.bs

See https://github.com/tc39/ecma262/pull/1314
***
<a href="https://whatpr.org/webidl/1415.html" title="Last updated on Jul 2, 2024, 3:08 AM UTC (d8b4793)">Preview</a> | <a href="https://whatpr.org/webidl/1415/4035d0a...d8b4793.html" title="Last updated on Jul 2, 2024, 3:08 AM UTC (d8b4793)">Diff</a>

Update `@@foo` symbol notation to `%Symbol.foo%` notation

---

index.bs

None of the code generation for named setters in any of the major browsers appears to honor Step 3. of 3.9.3. [[DefineOwnProperty]]( https://webidl.spec.whatwg.org/#legacy-platform-object-defineownproperty).
The test case in WPT
(http://wpt.live/dom/collections/HTMLCollection-supported-property-names.html) already appears to assert that the descriptor is not forced to become [[Configurable]], and this test case is passing in most implementations.
I've done a bunch of detective work to justify this 2 line patch, so dumping all of that here. commit hashes are current as of writing this.
WebKit:
https://github.com/WebKit/WebKit/blob/f288b9088d1b74b980c3b7a8d5add134f7689bdb/Source/WebCore/bindings/scripts/CodeGeneratorJS.pm#L1545-L1551
Chromium: …

legacy platform objects no longer override desc.[[Configurable]]

---

index.bs

The new "transferable" algorithm allows an invoker to determine if a BufferSource can be detached without errors before invoking transfer. This is particularly helpful if several buffers are processed in a batch, as the validity of the operation can be determined up front, rather than during processing which could leave the buffers in a mix of states.
See discussion in [1]. A local copy of the algorithm was landed as [2] (as "detachable") but this seems like a useful addition to WebIDL.
1: https://github.com/webmachinelearning/webnn/issues/351
2: https://webmachinelearning.github.io/webnn/#buffersource-detachable
*Eliding the checklist since this is a helper algorithm not new functionality, but please ask if more details are desired*
***
<a href="https://whatpr.org/webidl/1419.html" …

Introduce a "transferable" algorithm for BufferSource

---

index.bs

This makes the algorithm more user-friendly, as this is generally the desired behavior, and the algorithm can already throw for other reasons so callers are expected to handle that.
/cc @inexorabletash as this was inspired by your work in https://github.com/whatwg/webidl/pull/1419.
I audited [the callers](https://dontcallmedom.github.io/webdex/t.html#transfer%40%40ArrayBuffer%40dfn) and they are all fine with this. (Most are just referencing the concept of transferring, as these definitions are not yet widely used.)
***
<a href="https://whatpr.org/webidl/1420.html" title="Last updated on Jul 18, 2024, 1:23 AM UTC (bf45161)">Preview</a> | <a href="https://whatpr.org/webidl/1420/3fb6ab4...bf45161.html" title="Last updated on Jul 18, 2024, 1:23 AM UTC (bf45161)">Diff</a>

Throw, instead of assert, for transferring detached ArrayBuffers

---

index.bs

This makes it more concise for users to, as is frequently desired for undefined-returning callbacks especially, immediately catch and report the exception rather than needing to handle it themselves.
This isn't appropriate for other types of callback functions, where a result may be expected or the exception needs to be rethrown. Callers need to explicitly decide which behavior they want, unless the callback returns a promise type, in which case exceptions are turned into rejected promises implicitly.
Fixes #1423.
***
<a href="https://whatpr.org/webidl/1424.html" title="Last updated on Aug 2, 2024, 5:35 AM UTC (000a709)">Preview</a> | <a …

Allow users of "invoke a callback function" to report the exception

---

index.bs

The previous text assumed that the AllocateArrayBuffer step would never throw, since it was basically spec fiction for retargeting a pointer. However, if we transfer across agent clusters, memory allocation will be needed. And even then, we shouldn't be normatively asserting that implementations use the pointer-retargeting strategy. Instead, we can explain it in a note.
***
<a href="https://whatpr.org/webidl/1422.html" title="Last updated on Jul 19, 2024, 1:30 AM UTC (6a37390)">Preview</a> | <a href="https://whatpr.org/webidl/1422/155ae10...6a37390.html" title="Last updated on Jul 19, 2024, 1:30 AM UTC (6a37390)">Diff</a>

Stop assuming "transfer" is same-agent cluster

---

review-drafts/2024-09.bs

The [September 2024 Review Draft](https://webidl.spec.whatwg.org/review-drafts/2024-09/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/webidl/1433.html" title="Last updated on Sep 16, 2024, 7:53 AM UTC (d27e085)">Preview</a> | <a href="https://whatpr.org/webidl/1433/e7b2fe1...d27e085.html" title="Last updated on Sep 16, 2024, 7:53 AM UTC (d27e085)">Diff</a>

Review Draft Publication: September 2024

---

index.bs

Follows https://github.com/tc39/ecma262/pull/3395. Fixes #1444.
***
<a href="https://whatpr.org/webidl/1446.html" title="Last updated on Oct 28, 2024, 4:53 AM UTC (a9d3bf6)">Preview</a> | <a href="https://whatpr.org/webidl/1446/4381866...a9d3bf6.html" title="Last updated on Oct 28, 2024, 4:53 AM UTC (a9d3bf6)">Diff</a>

Fix Iterator prototype reference

---

index.bs

* …
* …
* … 
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
Fixes #1443
***
<a href="https://whatpr.org/webidl/1445.html" title="Last updated on Oct 29, 2024, 2:56 AM UTC (128fbfe)">Preview</a> | <a href="https://whatpr.org/webidl/1445/33c2eec...128fbfe.html" title="Last updated on Oct 29, 2024, 2:56 AM UTC (128fbfe)">Diff</a>

Promises: Return a PromiseCapability from react

---

index.bs

This is an attempt to fix https://github.com/tc39/proposal-is-error/issues/9.
The intention is to make DOM Exceptions true subclasses of `Error`.
It's possible this PR needs additional changes to simplify/undo #732 - I'm happy to make whatever changes are appropriate.
* Google
* Firefox
* https://github.com/web-platform-tests/wpt/pull/49133 
* Chromium: https://issues.chromium.org/issues/382104870
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1923733
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=284506
* Deno: gets it for free from v8
* Node.js: gets it for free from v8
* webidl2.js: n/a, i think?
* widlparser: n/a, i think?
This is part of a stage 2 TC39 proposal for `Error.isError`. When it advances to stage 2.7, I'll file the appropriate implementation bugs.
***
<a …

add [[ErrorData]] slot to DOMExceptions

---

index.bs

***
<a href="https://whatpr.org/webidl/1464.html" title="Last updated on Jan 24, 2025, 2:38 PM UTC (213e5f4)">Preview</a> | <a href="https://whatpr.org/webidl/1464/acbbd5f...213e5f4.html" title="Last updated on Jan 24, 2025, 2:38 PM UTC (213e5f4)">Diff</a>

Meta: address Bikeshed errors

---

review-drafts/2025-03.bs

The [March 2025 Review Draft](https://webidl.spec.whatwg.org/review-drafts/2025-03/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/webidl/1479.html" title="Last updated on Mar 17, 2025, 4:24 PM UTC (8f49975)">Preview</a> | <a href="https://whatpr.org/webidl/1479/f810464...8f49975.html" title="Last updated on Mar 17, 2025, 4:24 PM UTC (8f49975)">Diff</a>

Review Draft Publication: March 2025

---

index.bs

This changes the `async iterable` grammar added by #1397 to `async_iterable` so that the grammar can stay within `LL(1)` rule.
Fixes https://github.com/whatwg/webidl/issues/1490
* Apple per annevk's approval
* Gecko by me
* N/A (can't test without an actual API that use it)
* Chromium: https://issues.chromium.org/issues/356891478#comment2
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1911295#c1
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=277548#c2
* Deno: https://github.com/denoland/deno/issues/30020
* Node.js: https://github.com/nodejs/node/issues/54175#issuecomment-3044841232
* webidl2.js: https://github.com/w3c/webidl2.js/pull/775#discussion_r2189808923 (the comment is enough for me as a maintainer)
* widlparser: https://github.com/plinss/widlparser/issues/90
(See [WHATWG …

Replace incorrect "async iterable" token to "async_iterable"

---

index.bs

This changes the `async_iterable<>` type to `async_sequence<>`, to avoid confusion with the interface declaration, and change the `async iterable<>` interface declaration to `async_iterable<>`, to avoid future LL(1) issues.
* Apple per @annevk approval
* Mozilla per @saschanaz approval (in #1504)
* N/A, this is a grammar change in WebIDL itself
* Chromium: https://g-issues.chromium.org/issues/356891478#comment3 and https://g-issues.chromium.org/issues/433299826
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1911295#c2 and <https://bugzilla.mozilla.org/show_bug.cgi?id=1978444>
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=277548#c3 and https://bugs.webkit.org/show_bug.cgi?id=296291
* Deno: https://github.com/denoland/deno/issues/30020
* Node.js: …

Update all examples, and the lt for the type, to the new underscore'd token

---

index.bs

Do not throw if the attribute setter is called with no arguments
This is for https://github.com/whatwg/webidl/issues/1497 .
This changes the attribute setter not to throw if it's called with no arguments (this can happen only if the setter function is extracted from the property descriptor and directly called), and instead treat it as if `undefined` is passed.
No browsers had been following the previous behavior, and the updated behavior matches WebKit.
* WebKit (https://github.com/whatwg/webidl/issues/1497#issuecomment-3019315858)
* Chromium (https://github.com/whatwg/webidl/issues/1497#issuecomment-3021612289, https://github.com/whatwg/webidl/issues/1497#issuecomment-3021622854)
* Gecko (https://github.com/whatwg/webidl/issues/1497#issuecomment-3028206420 , and patch is ready in …

Do not throw if the attribute setter is called with no arguments

---

index.bs

The web platform benefits from having a type of exception that tells you about when you exceed quotas. In some cases, it can be helpful to tell you what the quota was, and by how much you exceeded it. https://github.com/webmachinelearning/writing-assistance-apis/issues/5 gives one specific use case.
The web platform already has an exception type for telling you when you exceed quotas: it is `DOMException`, with the specific `name` property set to `"QuotaExceededError"`. However, this does not allow carrying additional information.
This PR proposes removing `"QuotaExceededError"` from the list of built-in `DOMException` names, and instead creates a class named `QuotaExceededError` that derives from `DOMException` and has the additional optional properties `quota` and `requested`. We …

Upgrade QuotaExceededError to a DOMException derived interface

---

index.bs

Introduce four new extended attribute grammars
These new grammars will be used by the HTML spec for attribute reflection extended attributes. ExtendedAttributeString (`[Reflect="foo"]`), ExtendedAttributeInteger (`[ReflectDefault=1]`), ExtendedAttributeDecimal (`[ReflectDefault=1.0]`) and ExtendedAttributeIntegerList (`[ReflectRange=(1,100)]`) are added.
* …
* …
* N/A
* Chromium: N/A
* Gecko: N/A
* WebKit: N/A
* Deno: N/A
* Node.js: N/A
* webidl2.js: https://github.com/w3c/webidl2.js/issues/817
* widlparser: https://github.com/plinss/widlparser/issues/91
***
<a href="https://whatpr.org/webidl/1503.html" title="Last updated on Jul 17, 2025, 6:09 PM UTC (191ffa7)">Preview</a> | <a …

Introduce new extended attribute grammars
