whatwg/webidl

index.html, index.xml
Fixes <https://www.w3.org/Bugs/Public/show_bug.cgi?id=26984>.
=> Remove the legacyiterable keyword.

index.html, index.xml
This fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=22824
=> Remove the Date type.

index.xml
There are six special operations after creator was removed.
=> Fix typo in special operations

index.xml
This uses [Bikeshed's markup](https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md) like #105.
=> Link the common typedefs, and fix FrozenArray's lt attribute.

index.html, index.xml
=> Add missing 'return's.

index.bs, index.html
Bikeshed now fatals if dictionaries will only optional members aren't marked as optional themselves, per spec.
=> Update to latest Bikeshed

index.bs, index.html
These got lost during the conversion process.
Closes #161.
=> Fix calls to the create a sequence from an iterable algorithm.

README.md
=> docs(README): contributing section (closes #136)

index.bs, index.html
Add a few missing dfns in the process.
=> Convert idl- prefixed anchors to Bikeshed notation.

index.bs, index.html
It's nice to get to the good stuff sooner.
=> Move conventions and conformance to appendices

README.md
<hr />
[Preview](https://rawgit.com/jyasskin/webidl/patch-1/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Fjyasskin%2Fwebidl%2Fpatch-1%2Findex.html)
=> Define the language the spec is written in.

index.bs, index.html
This helps grasp the structure of the spec and orientate yourself within it.
<hr />
[Preview](https://rawgit.com/tobie/webidl/scrollspy/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Ftobie%2Fwebidl%2Fscrollspy%2Findex.html)
=> Add scroll spy.

index.bs, index.html
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=26490.
<hr />
[Preview](https://rawgit.com/tobie/webidl/is-ext/index.html) (<a href="https://rawgit.com/tobie/webidl/is-ext/index.html#named-properties-object-preventextensions" title="#named-properties-object-preventextensions">#named-pro…</a>) (<a href="https://rawgit.com/tobie/webidl/is-ext/index.html#indexed-and-named-properties" title="#indexed-and-named-properties">#indexed-a…</a>) (<a href="https://rawgit.com/tobie/webidl/is-ext/index.html#preventextensions" title="#preventextensions">#preventex…</a>) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Ftobie%2Fwebidl%2Fis-ext%2Findex.html) (<a href="https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.gith …
=> Make [[PreventExtensions]] fail for objects with named/indexed props.

index.bs, index.html
Closes #200.
<hr />
[Preview](https://rawgit.com/tobie/webidl/detach-buff/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Ftobie%2Fwebidl%2Fdetach-buff%2Findex.html) 
<details><summary>Per Commit Preview &amp; Diffs</summary><code title="Merge algo and dfn for &quot;detaching an ArrayBuffer&quot;">62dabd2</code>: [Preview](https://cdn.rawgit.com/tobie/webidl/62dabd2/index.html) | [Diff w/ Head](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F62dabd2%2Findex.html)  _(2016-10-27 09:50)_
Latest (<code title="Proper ES6 notation&period;">8e65360</code>): [Preview](https://cdn.rawgit.com/tobie/webidl/8e65360/index.html) | …
=> Merge algo and dfn for "detaching an ArrayBuffer"

index.bs, index.html
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29450.
***
[Preview](https://rawgit.com/heycam/webidl/annevk/security-check/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Frawgit.com%2Fheycam%2Fwebidl%2Fannevk%2Fsecurity-check%2Findex.html)
=> Remove realm argument of "perform a security check"

index.bs, index.html
Fixes #148
Fixes #145
***
[Preview](https://cdn.rawgit.com/tobie/webidl/00b9786/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F00b9786%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F001ba52%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F00b9786%2Findex.html)
=> Remove all references to RegExp.

index.bs, index.html
***
[Preview](https://cdn.rawgit.com/TimothyGu/webidl/7e31f4a/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2FTimothyGu%2Fwebidl%2F7e31f4a%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F2070d80%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2FTimothyGu%2Fwebidl%2F7e31f4a%2Findex.html)
=> Add missing index increment and use index variable

README.md
=> Add instructions on when & where to file issues

index.bs, index.html
- Wrap it in `<div algorithm>`
- Return |F|
- Use |op| appropriately
---
Separated from https://github.com/heycam/webidl/pull/217. Use this URL to view the changes without whitespace: https://github.com/heycam/webidl/pull/232/files?w=1
***
[Preview](https://cdn.rawgit.com/heycam/webidl/6a0e09c/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F6a0e09c%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Ff3c9521%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F6a0e09c%2Findex.html)
=> Minor fixups to creating an operation Function

index.bs, index.html
Ready for comments, not ready to be merged.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/fc8ba8b/index.html#es-integer-types) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Ffc8ba8b%2Findex.html#es-integer-types) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F3bf3f84%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Ffc8ba8b%2Findex.html#es-integer-types)
=> Refactor integer conversion in ES bindings.

index.bs, index.html
***
[Preview](https://cdn.rawgit.com/heycam/webidl/bf04763/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fbf04763%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F36168b7%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fbf04763%2Findex.html)
=> Meta: export record mappings

index.bs, index.html
Closes https://github.com/heycam/webidl/issues/204
***
[Preview](https://cdn.rawgit.com/tobie/webidl/05b547e/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F05b547e%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F3796857%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F05b547e%2Findex.html)
=> Editorial: use <var ignore> instead of Ignored Vars.

index.bs, index.html
Fixes: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27732
Fixes: https://wicg.github.io/entries-api/#issue-bfc3b40a
***
[Preview](https://cdn.rawgit.com/tobie/webidl/823a0f0/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F823a0f0%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F671706d%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F823a0f0%2Findex.html)
=> Add missing legacy error names.

index.bs, index.html
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25049
***
[Preview](https://cdn.rawgit.com/tobie/webidl/1f8fd95/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F1f8fd95%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fc50ffc4%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F1f8fd95%2Findex.html)
=> Disallow nullable Promise types.

index.bs, index.html
Amends #250 and fixes #247.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/3b60be5/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F3b60be5%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fc2d602f%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2F3b60be5%2Findex.html)
=> Meta: fix "throw" dfns

index.bs, index.html
=> Fix incorrect [LenientThis] that should be [LenientSetter]

index.bs, index.html
Closes #199.
***
[Preview](https://cdn.rawgit.com/tobie/webidl/c1c6671/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fc1c6671%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fdca1688%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Ftobie%2Fwebidl%2Fc1c6671%2Findex.html)
=> Editorial: objects support named/index properties by extension

index.bs, index.html
This allows https://github.com/whatwg/url/issues/137 to move on.
***
[Preview](https://cdn.rawgit.com/heycam/webidl/e71e0ac/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fe71e0ac%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F80a304b%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2Fe71e0ac%2Findex.html)
=> Drop toJSON as reserved identifier

index.bs, index.html
Fixes #295 and fixes #297.
@bzbarsky How's this?
=> Ban nullable records in dictionary members and operation arguments.

index.bs, index.html
***
[Preview](https://cdn.rawgit.com/xfq/webidl/7d4c167/index.html) | [Diff w/ current ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fheycam.github.io%2Fwebidl%2F&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fxfq%2Fwebidl%2F7d4c167%2Findex.html) | [Diff w/ base](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.rawgit.com%2Fheycam%2Fwebidl%2F20b87a7%2Findex.html&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fxfq%2Fwebidl%2F7d4c167%2Findex.html)
=> Fix an example of serialization behavior

index.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/bzbarsky/webidl/fix-silly-grammar.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/26aa830..bzbarsky:fix-silly-grammar:16e891d.html)
=> Make the situation with [] default values a bit clearer.

index.bs
Closes #255.
Closes #257.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-257.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/53cbeef..tobie:fix-257:2eb8839.html)
=> Cleanup DOMException.

index.bs
Closes #244.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/legacy-caller.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/36b3646...tobie:3dfc536.html)
=> Editorial: markup legacy caller correctly

index.bs
Closes #330.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-330.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/9e0d636...tobie:77359c3.html)
=> Editorial: fix incorrect count.

index.bs
Temporary fix to #201.
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/tmp-fix-201.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/d732f98...tobie:5e98775.html)
=> Replace default [[Set]] by OrdinarySet.

README.md
/cc @cdumez: does the default here sound reasonable to file WebIDL-related issued?
=> Add dedicated URL for filing bugs with WebKit

README.md
Closes #267.
/cc @rbyers: please LMK if/how this can be improved. Thanks.
=> Add bug template URL for Chromium

index.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/cleanup-grammar.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/fb40c8e...tobie:e3c1dc7.html)
=> Remove orphaned Inherit non-terminal

index.bs
Fixes #368.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/attr-setter-set.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/14792cb...TimothyGu:6fa0b83.html)
=> Specify all arguments to Set in attribute setter

index.bs
Fixes #309.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/distinguishable-types.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/8b83d25...TimothyGu:1ac86ab.html)
=> Clarify value vs type in distinguishability categories

index.bs
Fixes #414.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/exception-handling-update.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/48f1e62...TimothyGu:c6752b0.html)
=> Update and link ES exception handling

index.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-clamp.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/2b1a990...tobie:d375d36.html)
=> Editorial: fix copy/paste error in [EnforceRange] section

index.bs
Fixes #446.
/cc @SaschaNaz
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/webidl/nullable-constant.html) | [Diff](https://s3.amazonaws.com/pr-preview/heycam/webidl/f97da39...TimothyGu:3c4eb7b.html)
=> Clarify nullable types for constants

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/482.html" title="Last updated on Dec 3, 2017, 7:36 PM GMT (a4cd029)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/a578ac5...TimothyGu:a4cd029.html" title="Last updated on Dec 3, 2017, 7:36 PM GMT (a4cd029)">Diff</a>
=> Add missing full stops

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/493.html" title="Last updated on Dec 10, 2017, 11:03 PM GMT (f3593f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/493/4fcfaea...tobie:f3593f0.html" title="Last updated on Dec 10, 2017, 11:03 PM GMT (f3593f0)">Diff</a>
=> Editorial: cleanup platform and legacy platform object descriptions

index.bs
References #450.
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/499.html" title="Last updated on Dec 14, 2017, 9:36 PM GMT (ac5ba00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/499/f41e450...tobie:ac5ba00.html" title="Last updated on Dec 14, 2017, 9:36 PM GMT (ac5ba00)">Diff</a>
=> Meta: fix markup now that Bikeshed supports mixins

index.bs
Closes #529.
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/530.html" title="Last updated on Mar 2, 2018, 9:18 AM GMT (53d9c84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/530/4e32b14...tobie:53d9c84.html" title="Last updated on Mar 2, 2018, 9:18 AM GMT (53d9c84)">Diff</a>
=> Editorial: export "includes" dfn.

index.bs
Closes #496.
***
<a href="https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/494.html" title="Last updated on Apr 10, 2018, 3:07 PM GMT (eddf233)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/494/41bc728...tobie:eddf233.html" title="Last updated on Apr 10, 2018, 3:07 PM GMT (eddf233)">Diff</a>
=> Make interface prototype object creation imperative

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webidl/pull/575.html" title="Last updated on Jul 21, 2018, 8:58 PM GMT (80a02b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/575/0326142...foolip:80a02b2.html" title="Last updated on Jul 21, 2018, 8:58 PM GMT (80a02b2)">Diff</a>
=> Editorial: add missing [ for [SecureContext]

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/afdw/webidl/pull/576.html" title="Last updated on Aug 5, 2018, 10:27 PM GMT (62b64d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/576/33031fc...afdw:62b64d0.html" title="Last updated on Aug 5, 2018, 10:27 PM GMT (62b64d0)">Diff</a>
=> Fix a place forgotten in #519

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/afdw/webidl/pull/578.html" title="Last updated on Aug 10, 2018, 9:43 AM GMT (583ef61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/578/4afb5e8...afdw:583ef61.html" title="Last updated on Aug 10, 2018, 9:43 AM GMT (583ef61)">Diff</a>
=> Further cleanup following #573

index.bs
Fixes #381.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/610.html" title="Last updated on Jan 14, 2019, 4:31 PM UTC (2ca8a5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/610/6ec828c...Ms2ger:2ca8a5f.html" title="Last updated on Jan 14, 2019, 4:31 PM UTC (2ca8a5f)">Diff</a>
=> Use map/exists to define dictionary/present.

index.bs
Fixes #548.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/615.html" title="Last updated on Jan 15, 2019, 2:22 PM UTC (a748560)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/615/d05c8cc...Ms2ger:a748560.html" title="Last updated on Jan 15, 2019, 2:22 PM UTC (a748560)">Diff</a>
=> Editorial: Clarify the wording of an Exposed requirement.

index.bs
Fixes #572.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/614.html" title="Last updated on Jan 15, 2019, 1:47 PM UTC (52e114e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/614/d05c8cc...Ms2ger:52e114e.html" title="Last updated on Jan 15, 2019, 1:47 PM UTC (52e114e)">Diff</a>
=> Disallow Replaceable on namespaces, and fix the attribute setter creation.

index.bs
Fixes #534.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/619.html" title="Last updated on Jan 16, 2019, 10:43 AM UTC (32e54b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/619/ce7b02c...Ms2ger:32e54b3.html" title="Last updated on Jan 16, 2019, 10:43 AM UTC (32e54b3)">Diff</a>
=> Editorial: Make the opName argument required.

index.bs
Fixes #207.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/618.html" title="Last updated on Jan 29, 2019, 10:17 AM UTC (213d0c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/618/ce7b02c...Ms2ger:213d0c0.html" title="Last updated on Jan 29, 2019, 10:17 AM UTC (213d0c0)">Diff</a>
=> Fix error handling around Call().

index.bs
Apparently, we forgot.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/641.html" title="Last updated on Feb 7, 2019, 4:47 PM UTC (9151748)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/641/fc5da8f...9151748.html" title="Last updated on Feb 7, 2019, 4:47 PM UTC (9151748)">Diff</a>
=> Define the static operations on the interface object

index.bs
This was changed in https://github.com/tc39/ecma262/pull/1101.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/642.html" title="Last updated on Feb 11, 2019, 12:49 PM UTC (1525447)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/642/7fdbf9d...1525447.html" title="Last updated on Feb 11, 2019, 12:49 PM UTC (1525447)">Diff</a>
=> Editorial: use the new signature of CreateBuiltinFunction

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/644.html" title="Last updated on Feb 12, 2019, 4:01 PM UTC (b0be5a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/644/eb67e79...b0be5a1.html" title="Last updated on Feb 12, 2019, 4:01 PM UTC (b0be5a1)">Diff</a>
=> Use PerformPromiseThen to perform some steps once a promise is settled

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/646.html" title="Last updated on Feb 13, 2019, 11:39 AM UTC (07da6d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/646/49d911b...07da6d1.html" title="Last updated on Feb 13, 2019, 11:39 AM UTC (07da6d1)">Diff</a>
=> Editorial: correct 'callback interface' cross-reference

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/647.html" title="Last updated on Feb 19, 2019, 10:36 AM UTC (afb56aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/647/7769c5f...afb56aa.html" title="Last updated on Feb 19, 2019, 10:36 AM UTC (afb56aa)">Diff</a>
=> Add a Privacy and Security Considerations section

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/672.html" title="Last updated on Mar 1, 2019, 4:14 PM UTC (5b952ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/672/c705ce6...5b952ce.html" title="Last updated on Mar 1, 2019, 4:14 PM UTC (5b952ce)">Diff</a>
=> Editorial: fix some bikeshed link warnings

index.bs
Closes #677
***
<a href="https://pr-preview.s3.amazonaws.com/littledan/webidl/pull/678.html" title="Last updated on Mar 4, 2019, 12:58 PM UTC (d3e710b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/678/1bf01fa...littledan:d3e710b.html" title="Last updated on Mar 4, 2019, 12:58 PM UTC (d3e710b)">Diff</a>
=> Editorial: Clarify that attributes and operations may be namespace members

index.bs
/cc @heycam
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/685.html" title="Last updated on Mar 10, 2019, 9:10 PM UTC (3b3bc26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/685/b4f9467...3b3bc26.html" title="Last updated on Mar 10, 2019, 9:10 PM UTC (3b3bc26)">Diff</a>
=> Editorial: marking former editors as such

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/684.html" title="Last updated on Mar 11, 2019, 10:32 AM UTC (e1fd1db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/684/b4f9467...e1fd1db.html" title="Last updated on Mar 11, 2019, 10:32 AM UTC (e1fd1db)">Diff</a>
=> Properly call the imperative creation algorithms for prototypes

index.bs
Fixes #661.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/696.html" title="Last updated on Apr 2, 2019, 1:59 PM UTC (fdeb0a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/696/7ce9ef8...fdeb0a9.html" title="Last updated on Apr 2, 2019, 1:59 PM UTC (fdeb0a9)">Diff</a>
=> Remove unused callback interface functionality

index.bs
=> Editorial: Remove a duplicate emu-nt start tag

index.bs
Fixes #308.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/727.html" title="Last updated on May 14, 2019, 10:59 AM UTC (cb1d4f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/727/c1172cc...cb1d4f2.html" title="Last updated on May 14, 2019, 10:59 AM UTC (cb1d4f2)">Diff</a>
=> Editorial: Provide a definition for "compute an effective overload set" and use it

index.bs
See <https://github.com/tc39/ecma262/pull/1312>.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/741.html" title="Last updated on Jun 25, 2019, 3:18 PM UTC (51559c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/741/815f5ae...51559c7.html" title="Last updated on Jun 25, 2019, 3:18 PM UTC (51559c7)">Diff</a>
=> Rename Module.Instantiate to Module.Link

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/742.html" title="Last updated on Jun 26, 2019, 10:16 AM UTC (43a36bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/742/c0d927a...43a36bf.html" title="Last updated on Jun 26, 2019, 10:16 AM UTC (43a36bf)">Diff</a>
=> Use IDL this for the synthetic forEach method.

index.bs
Fixes #740.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/746.html" title="Last updated on Jun 28, 2019, 9:34 AM UTC (b5551b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/746/c0d927a...b5551b7.html" title="Last updated on Jun 28, 2019, 9:34 AM UTC (b5551b7)">Diff</a>
=> Disallow Promise types in unions at the syntax level.

index.bs
Fixes #754.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/764.html" title="Last updated on Aug 6, 2019, 2:10 PM UTC (ecb97ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/764/5c57dc1...ecb97ec.html" title="Last updated on Aug 6, 2019, 2:10 PM UTC (ecb97ec)">Diff</a>
=> Editorial: Add syntax highlighting to an example.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/771.html" title="Last updated on Aug 20, 2019, 1:10 PM UTC (137048d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/771/94c320e...137048d.html" title="Last updated on Aug 20, 2019, 1:10 PM UTC (137048d)">Diff</a>
=> Editorial: Fix markup in DOMException section.

index.bs
Fixes #490.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/772.html" title="Last updated on Aug 27, 2019, 9:45 AM UTC (c3fcded)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/772/34ef605...c3fcded.html" title="Last updated on Aug 27, 2019, 9:45 AM UTC (c3fcded)">Diff</a>
=> Import the Promises Guide.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/785.html" title="Last updated on Sep 2, 2019, 8:04 AM UTC (74955d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/785/91ca6eb...74955d9.html" title="Last updated on Sep 2, 2019, 8:04 AM UTC (74955d9)">Diff</a>
=> Clarify the relation between the secure context definitions.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/821.html" title="Last updated on Nov 11, 2019, 5:03 PM UTC (fb466a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/821/d87d389...fb466a3.html" title="Last updated on Nov 11, 2019, 5:03 PM UTC (fb466a3)">Diff</a>
=> Fix typo: inferface.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/anpol/webidl/pull/834.html" title="Last updated on Jan 21, 2020, 1:09 PM UTC (5564b02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/834/d93ee24...anpol:5564b02.html" title="Last updated on Jan 21, 2020, 1:09 PM UTC (5564b02)">Diff</a>
=> Fix typo: protoype

index.bs
I am moving on to other things.  Edgar has volunteered to take over editing, and the Web IDL binding implementation in Gecko.
@EdgarChen @Ms2ger @domenic @marcoscaceres @heycam @annevk
***
<a href="https://pr-preview.s3.amazonaws.com/bzbarsky/webidl/pull/849.html" title="Last updated on Mar 10, 2020, 9:10 PM UTC (0e5ae51)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/849/225a115...bzbarsky:0e5ae51.html" title="Last updated on Mar 10, 2020, 9:10 PM UTC (0e5ae51)">Diff</a>
=> Stepping down as editor

Makefile, deploy.sh
Avoids duplication and hopefully keeps strictness consistent.
@tobie @domenic @Ms2ger any reason these are not in sync? I noticed the build script not failing with https://github.com/heycam/webidl/pull/848 while it was failing locally.
=> Meta: use Makefile from deploy.sh

index.bs
This should’ve been uncommented as part of <https://github.com/heycam/webidl/pull/483>.
***
<a href="https://pr-preview.s3.amazonaws.com/EB-Forks/webidl/pull/858.html" title="Last updated on Mar 18, 2020, 5:55 PM UTC (5cc1dd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/858/691b8d2...EB-Forks:5cc1dd2.html" title="Last updated on Mar 18, 2020, 5:55 PM UTC (5cc1dd2)">Diff</a>
=> docs(iterable): GH-419 is fixed

index.bs
Mentioned in passing in https://github.com/heycam/webidl/pull/859.
***
<a href="https://pr-preview.s3.amazonaws.com/TimothyGu/webidl/pull/864.html" title="Last updated on Mar 26, 2020, 1:09 AM UTC (2120e0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/864/8d4e7ca...TimothyGu:2120e0c.html" title="Last updated on Mar 26, 2020, 1:09 AM UTC (2120e0c)">Diff</a>
=> Editorial: Cite API design principles for default true advisement

index.bs
CC #748.
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/749.html" title="Last updated on Apr 29, 2020, 3:33 PM UTC (351e093)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/749/350fb2a...351e093.html" title="Last updated on Apr 29, 2020, 3:33 PM UTC (351e093)">Diff</a>
=> Editorial: Better explanation of the Global extended attribute.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/773.html" title="Last updated on Oct 14, 2019, 5:45 PM UTC (d5b0db6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/773/34ef605...d5b0db6.html" title="Last updated on Oct 14, 2019, 5:45 PM UTC (d5b0db6)">Diff</a>
=> Minor grammar cleanup

index.bs
This is per https://github.com/heycam/webidl/pull/891#pullrequestreview-428867352.
=> Editorial: Add Timothy as an editor

index.bs
This fixes a few things that I noticed that I believe are spelling errors.
=> A few spelling fixes.

index.bs
=> Allow constants on namespaces

index.bs
Closes #1000.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 29, 2021, 12:23 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fheycam%2Fwebidl%2F008d7cb6b579aff1f4663677d744fdb3cb4687f3%2Findex.bs&md-warning=not%20ready)
```
<html><body><p><strong>WARNING: </strong>mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' …
```
=> ObservableArray type should only be allowed on interface

README.md
This endpoint lets one select the issue template before filing.
=> chore(README): update webidl2.js issues endpoint

index.bs
See https://github.com/triple-underscore/triple-underscore.github.io/issues/1#issuecomment-935577516.
=> Link Japanese translation

index.bs
I never did so in my previous edits ^_^
***
<a href="https://whatpr.org/webidl/1110.html" title="Last updated on Feb 28, 2022, 8:03 PM UTC (b20fe06)">Preview</a> | <a href="https://whatpr.org/webidl/1110/ae0de45...b20fe06.html" title="Last updated on Feb 28, 2022, 8:03 PM UTC (b20fe06)">Diff</a>
=> Add self to acks

index.bs
Fixes #1087.
***
<a href="https://whatpr.org/webidl/1088.html" title="Last updated on Jan 24, 2022, 7:48 AM UTC (68694d0)">Preview</a> | <a href="https://whatpr.org/webidl/1088/ab25fa4...68694d0.html" title="Last updated on Jan 24, 2022, 7:48 AM UTC (68694d0)">Diff</a>
=> Correct [Global] example

index.bs
***
<a href="https://whatpr.org/webidl/1201.html" title="Last updated on Sep 27, 2022, 6:08 AM UTC (594b052)">Preview</a> | <a href="https://whatpr.org/webidl/1201/b03aa9e...594b052.html" title="Last updated on Sep 27, 2022, 6:08 AM UTC (594b052)">Diff</a>
=> Meta: assume the browser supports CSS transforms

index.bs
Fixes #1136.
* …
* …
* https://github.com/web-platform-tests/wpt/pull/36133
* Chrome: …
* Firefox: …
* Safari: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/webidl/1137.html" title="Last updated on Sep 28, 2022, 2:54 PM UTC (1afe878)">Preview</a> | <a href="https://whatpr.org/webidl/1137/271cff8...1afe878.html" title="Last updated on Sep 28, 2022, 2:54 PM UTC (1afe878)">Diff</a>
=> Expose DOMException everywhere.

index.bs
Follows https://github.com/whatwg/html/commit/4ce0c6ca22c1e8cbeb84778d60c66282a669bc52.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 8, 2022, 1:13 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Fwebidl%2Fbf88a5afb980e4781a73a0e3febef2a5d757618a%2Findex.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%201212)
_If you don't have enough information above to solve the error by yourself …
=> Editorial: lowercase realm

index.bs
Fixes #1080.
This is an editorial change.
***
<a href="https://whatpr.org/webidl/1234.html" title="Last updated on Nov 21, 2022, 5:05 PM UTC (1703900)">Preview</a> | <a href="https://whatpr.org/webidl/1234/dcde683...1703900.html" title="Last updated on Nov 21, 2022, 5:05 PM UTC (1703900)">Diff</a>
=> Use the term scalar value from Infra

index.bs
@hsivonen inspired me to create this follow-up PR.
***
<a href="https://whatpr.org/webidl/1235.html" title="Last updated on Nov 22, 2022, 4:01 PM UTC (19493b4)">Preview</a> | <a href="https://whatpr.org/webidl/1235/0b4928e...19493b4.html" title="Last updated on Nov 22, 2022, 4:01 PM UTC (19493b4)">Diff</a>
=> Editorial: align code point formatting with Infra

index.bs
***
<a href="https://whatpr.org/webidl/1318.html" title="Last updated on Jun 5, 2023, 11:46 AM UTC (c0563c9)">Preview</a> | <a href="https://whatpr.org/webidl/1318/fcbaa09...c0563c9.html" title="Last updated on Jun 5, 2023, 11:46 AM UTC (c0563c9)">Diff</a>
=> Editorial: remove stray period

index.bs
***
<a href="https://whatpr.org/webidl/1355.html" title="Last updated on Aug 31, 2023, 6:56 AM UTC (739441d)">Preview</a> | <a href="https://whatpr.org/webidl/1355/84c4ccc...739441d.html" title="Last updated on Aug 31, 2023, 6:56 AM UTC (739441d)">Diff</a>
=> Meta: use XXX as issue class

index.bs
Fixes #1296.
***
<a href="https://whatpr.org/webidl/1372.html" title="Last updated on Oct 23, 2023, 1:28 AM UTC (80d4474)">Preview</a> | <a href="https://whatpr.org/webidl/1372/68db2ec...80d4474.html" title="Last updated on Oct 23, 2023, 1:28 AM UTC (80d4474)">Diff</a>
=> Editorial: Fix grammar in [LegacyNamespace] definition and improve markup

index.bs
***
<a href="https://whatpr.org/webidl/1452.html" title="Last updated on Nov 19, 2024, 1:52 PM UTC (5b9554d)">Preview</a> | <a href="https://whatpr.org/webidl/1452/0675b96...5b9554d.html" title="Last updated on Nov 19, 2024, 1:52 PM UTC (5b9554d)">Diff</a>
=> Editorial: define boolean and integer types in terms of Infra

.github/workflows/build.yml, .gitignore, PULL_REQUEST_TEMPLATE.md
See https://github.com/whatwg/spec-factory for details.
=> Meta: update repository files
